### ISSUE TITLE
Về việc giữ bản song ngữ

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#136]
Theo [đề xuất của nhiều người](https://www.facebook.com/groups/machinelearningcoban/permalink/795413900916019/), chúng ta nên giữ bản song ngữ để cả người mới bắt đầu và người đã có kinh nghiệm đọc đối chiếu để hiểu hơn. Mình thấy việc này hợp lý. Ngoài ra, việc giữ lại bản tiếng Anh cũng giúp bạn đọc đóng góp cách dịch tốt hơn.

Từ giờ trở đi, các chương mới sau khi được merge sẽ giữ cả tiếng Anh và tiếng Việt. Mình đề xuất để tiếng Anh lùi đầu dòng như dưới đây:

--------
> # English

Tiếng Việt
--------

Các bạn thấy thế nào?

**Comment by khoangothe** [comment]
Em thấy cũng hợp lý, vì sau này nếu muốn áp dụng những library hay framework vdu như tensorflow hay keras thì cũng phải biết thuật ngữ tiếng anh mới sử dụng được. Em nghĩ sau này có sách thì cũng nên add glossary của mình vào bản cuối cùng.

**Comment by tiepvupsu** [comment]
'Glossary' thì vẫn phải có.

Ý ảnh là bản song ngữ như [bản này](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/tiep_song_ngu_chap_1/chapters/ch01.md).

**Comment by ngcthuong** [comment]
Mình thì đề suất để 2 bản riêng biệt. 
1 bản hoàn toàn tiếng Việt
1 bản có cả hai tiếng. 

Không biết mọi người đọc sách song ngữ chưa chứ sách song ngữ mình thấy không phỏ biến bằng sacsh thường. **_Lúc in lại tốn ra gấp đôi_**. Nhiều người dùng không cần thiết phải có 2 bản, hoặc hoàn toàn có thể mở 2 tab Anh - tài liệu gốc và Việt tài liệu dịch. Vì mỗi chương ở đây rất ngắn.

**Comment by tiepvupsu** [comment]
À, đến cuối cùng sau khi dịch trơn tru sẽ làm bản tiếng Việt riêng. Hiện tại để song ngữ cho tiện việc dịch và hiểu. Khi nào xong hết thì làm thêm bản chỉ tiếng Việt. Lúc xong hết mới làm để tiết kiệm công sức copy/paste.
