### ISSUE TITLE
Góp ý bản dịch Chương 1-

### ISSUE THREAD

**Issue by freeloneman** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#142]
Thay đổi kiến trúc mạng **nerual** (ví dụ: hàm activation, số lượng nút ẩn, .v.v) 
-> sai chính tả chữ neural

If you choose well among these possible directions, you’ll build the leading cat picture platform, and lead your company to success. If you choose poorly, you might waste months. How do you proceed?
Nếu chọn đúng **một** trong những hướng kể trên, có thể bạn sẽ xây dựng nên một nền tảng ảnh mèo và startup thành công. Ngược lại, nếu chọn nhầm hướng, bạn có thể đánh mất cả tháng trời. Vậy phải làm như thế nào?
-> Nếu bạn làm tốt việc lựa chọn trong số các phương án kể trên thì bạn sẽ xây dựng được một nền tảng hàng đầu về ảnh mèo và đưa công ty bạn đến thành công. Nhưng nếu ngược lại thì bạn có thể đã lãng phí nhiều tháng trời. Vậy bạn phải làm như thế nào?

This book will tell you how. Most machine learning problems leave clues that tell you what’s useful to try, and what’s not useful to try. Learning to read those clues will save you months or years of development time.
Cuốn sách này sẽ giúp bạn trả lời câu hỏi đó. Phần lớn các vấn đề về machine learning đều có những **dấu hiệu riêng ẩn chứa gợi ý về phương hướng giải quyết**. Việc học để phát hiện ra những dấu hiệu đó sẽ giúp bạn tiết kiệm hàng tháng hay thậm chí hàng năm trời phát triển sản phẩm.
-> Cuốn sách này sẽ giúp bạn trả lời câu hỏi đó. Phần lớn các vấn đề về machine learning đều để lại các manh mối giúp bạn biết cái nào tốt để thử, cái nào không. Việc nghiên cứu để phát hiện ra những manh mối này sẽ giúp bạn tiết kiệm nhiều tháng hay thậm chí nhiều năm trời phát triển sản phẩm.

**Comment by ngcthuong** [comment]
Bạn vui lòng lập Pull Request khi góp ý bản dịch nhé. 

Và hiện nhóm đang ưu tiên các chương kế tiếp. Sau khi hoàn thiện một lượt sẽ thực hiện bước review lại từ đầu. 

Cách đóng góp cho dự án có thể xem chi tiết [ở đây](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/contribution.md)

**Comment by freeloneman** [comment]
Mình thấy đây là việc góp ý cho bản đã dịch, nếu tạo pull request sẽ qua nhiều bước mất thời gian. Nên làm issue để mọi người trao đổi rồi các bạn trong nhóm chủ repo sửa và pull lên nếu đồng ý, như vậy sẽ nhanh hơn. Bạn thấy làm như vậy có được không ? (thực tế mình chưa fork về máy mà chỉ muốn góp sức khi tiện thôi - ví dụ mở trên điện thoại).

**Comment by ngcthuong** [comment]
Làm như vậy tiện cho bạn nhưng bất tiện cho người review. Mình cũng chưa rõ có cách nào đẹp cả đôi bên được không. 

Thứ 2 là như mình nhắc ở trên. Nhóm ưu tiên đóng góp bản đạng dịch. Bạn có thể review bản đang dịch vậy là mức ưu tiên hơn và bạn cũng không cần fork về máy.

**Comment by freeloneman** [comment]
OK bạn. Mình mới tham gia nên cũng muốn review từ đầu theo thứ tự các chương. Vậy mình sẽ dùng 1 cái issue này (đổi tên) để review các chương đã dịch nhé, và mình nghĩ sẽ đuổi kịp để review các chương đang dịch.

**Comment by ngcthuong** [comment]
Vậy cũng ok. Nhóm sẽ back lại check bản rievew của bạn khi có thời gian hoặc hoàn thiện bản nháp toàn bộ quyển sách.

**Comment by freeloneman** [comment]
Chương 2

How to use this book to help your team
Cách sử dụng cuốn sách khi làm việc nhóm
-> Sử dụng cuốn sách này như thế nào để giúp ích cho nhóm của bạn

After finishing this book, you will have a deep understanding of how to set technical direction for a machine learning project.
Sau khi đọc xong cuốn sách này, bạn sẽ hiểu sâu hơn về cách lựa chọn hướng giải quyết kỹ thuật cho **đề tài** machine learning.
-> Sau khi đọc xong cuốn sách này, bạn sẽ hiểu sâu hơn về cách lựa chọn hướng giải quyết kỹ thuật cho một dự án machine learning.

**Comment by freeloneman** [comment]
Chương 3

I assume you are familiar with supervised learning: learning a function that maps from x to y, using labeled training examples (x,y). Supervised learning algorithms include linear regression, logistic regression, and neural networks. There are many forms of machine learning, but the majority of Machine Learning’s practical value today comes from supervised learning.
Tôi giả định rằng bạn đã quen thuộc với học có giám sát: học một **phương trình** ánh xạ từ x tới y, sử dụng các cặp dữ liệu có nhãn (x,y). Các thuật toán học có giám sát bao gồm hồi quy tuyến tính, hồi quy logistic và mạng neural. Machine Learning có rất nhiều **nhóm** tuy nhiên phần lớn các giá trị thực tiễn của nó hiện nay đến từ học có giám sát.
-> Tôi giả định rằng bạn đã quen thuộc với học có giám sát: học một hàm ánh xạ từ x tới y, sử dụng các cặp dữ liệu có nhãn (x,y). Các thuật toán học có giám sát bao gồm hồi quy tuyến tính, hồi quy logistic và mạng neural. Machine Learning có rất nhiều dạng tuy nhiên phần lớn các giá trị thực tiễn của nó hiện nay đến từ học có giám sát.

If you are not familiar with the concepts mentioned here, watch the first three weeks of videos in the Machine Learning course on Coursera at http://ml-class.org
Nếu những khái niệm nêu trên còn mới với bạn, bạn có thể đăng ký học ba tuần đầu lớp Machine Learning trên Coursera tại http://ml-class.org
-> Nếu những khái niệm nêu trên còn mới với bạn thì bạn hãy xem các video 3 tuần đầu tiên của khóa học Machine Learning trên Coursera tại http://ml-class.org

**Comment by tiepvupsu** [comment]
@freeloneman Tạo Pull Request và sửa trên bản hiện tại là cách tốt nhất để đóng góp vào các dự án cộng đồng. Đặc biệt là các dự án có sự tham gia của nhiều người.

Nó cũng giống như chức năng track change trên word và comment từng dòng từng từ luôn. Khi mọi người đồng ý thì merge là xong luôn. Còn khi bạn tạo issue thế này sẽ rất bất tiện cho việc review.

**Comment by tiepvupsu** [comment]
@freeloneman nhóm rất trân trọng những đóng góp của bạn. Nhưng như mình đã nói ở trên, nếu bạn paste mọi thứ vào đây sẽ không ai review hết được.
Nếu bạn đứng ở vị trí của một người tổng hợp, theo bạn mình sẽ tiếp nhận ý kiến của bạn và thay đổi bản gốc như thế nào? Chắc chắn mình không thể copy paste toàn bộ nội dung của bạn để thay thế được.

Việc tạo Pull Request có thể mới lạ với nhiều bạn, đặc biệt các bạn chưa quen code. Nhưng hiện tại nhóm chưa tìm ra giải phát nào hiệu quả hơn để việc review được thuận tiện.

Cảm ơn bạn nhiều.

**Comment by tiepvupsu** [comment]
@freeloneman f
mình đã tạo Pull request riêng tại #143, bạn comment trực tiếp vào dòng bạn muốn sửa nhé. Mình sẽ giúp bạn cập nhật PR này.

**Comment by freeloneman** [comment]
Mình đã comment cái PR đó, bạn xem giúp cách làm có đúng chưa nhé.
Tối mai mình sẽ fork về máy để tạo PR.

**Comment by tiepvupsu** [comment]
> Mình đã comment cái PR đó, bạn xem giúp cách làm có đúng chưa nhé.
> Tối mai mình sẽ fork về máy để tạo PR.

Cảm ơn bạn rất nhiều. Mình sẽ review khi có thời gian rảnh. Nếu bạn tạo PR mới thì làm cho từng chương riêng biệt để tiện review nhé. Chương 1 mình đã tạo rồi, bạn tạo các chương khác thôi.

**Comment by freeloneman** [comment]
Mình vừa tạo PR 152, các bạn kiểm tra xem cách làm đúng chưa nhé
