### ISSUE TITLE
Mỗi chương sẽ qua hai giai đoạn dịch

### ISSUE THREAD

**Issue by aivivn** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#147]
Mỗi chương dịch được chia làm hai giai đoạn:
* Giai đoạn 1: dịch thô, sát nghĩa, chưa cần trau chuốt
* Giai đoạn 2: chỉnh sửa cách dùng từ và hành văn.

Xem chi tiết cụ thể [tại đây](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/contribution.md).

**Các chương đã dịch mới trải qua giai đoạn 1.**

**Comment by ngcthuong** [comment]
Có cần đặt tiêu chí cho giai đoạn 1 khoảng thời gian dịch để tăng tiến độ?
Và cần review ở mức đọc tạm ổn như thế nào chứ không phải ở mức google translate?.
