### ISSUE TITLE
[Help - discuss only] Bị trùng branch khi commit

### ISSUE THREAD

**Issue by freeloneman** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#157]
Chào các bạn,
Mình tạo 2 Pull Request (PR) nhưng cái sau lại bị trùng file đã có trong cái trước. Để tránh tình trạng này lặp lại ở các PR tiếp theo mong các bạn xem giúp mình đã thao tác sai ở chỗ nào. Cụ thể như sau:
1. Chỉnh sửa file chapters/ch02.md
git branch bao-chapter2
git checkout bao-chapter2
git add . (vì chỉ có sửa duy nhất 1 file)
git commit
git push
Tạo PR
2. Chỉnh sửa file chapters/ch03.md
git branch bao-chapter3
git checkout bao-chapter3
git add .
git commit
git push
Tạo PR

Cảm ơn các bạn

**Comment by ngcthuong** [comment]
Bạn phải tạo branch khác. Mỗi branch chỉ edit 1 file thôi.

**Comment by freeloneman** [comment]
Khác branch mà bạn
bao-chapter2
bao-chapter3

**Comment by tiepvupsu** [comment]
Chào bạn, việc đó xảy ra vì khi bạn `git branch <branch_name>`, git sẽ tạo một branch mới **từ branch hiện tại**. Để tránh conflict, bạn phải tại một branh mới từ **master**.

Hiện tại bạn đang làm như sau:
```
___________________ master
\__________________bao-chapter2
                     \____________________bao-chapter3
```
nghĩa là `bao-chapter3` là một branch con của `bao-chapter2`. Tức là mọi thay đổi bạn tạo ở `bao-chapter2` cũng bị mang theo sang `bao-chapter3`.

Như dưới đây mới là đúng:
```
___________________ master
|          \__________________bao-chapter2
\_______________bao-chapter3
```

Ở hình dưới thì `bao-chapter3` không phụ thuộc vào `bao-chapter2`.

Để làm được việc này, trước hết bạn phải về master:
```
git checkout master
git checkout -b bao-chapter3
git add .
git commit
git push
```
Chú ý:
```
git checkout -b bao-chapter3
```
tương đương với:
```
git branch bao-chapter3
git checkout bao-chapter3
```

**Comment by tiepvupsu** [comment]
Một điểm đáng lưu ý nữa là bạn phải thường xuyên cập nhật repo này, vì nếu không bản của bạn đang sửa không phải bản mới nhất. Việc này được thực hiện bằng cách:
```
git pull https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation
```
khi đang ở trong repo của bạn.

**Comment by tiepvupsu** [comment]
Một mẹo nữa để xem cấu trúc của cả repo là dùng:
```
git log --all --graph --decorate --oneline
```
Ví dụ như ở repo này, mấy dòng đầu sẽ có dạng:
```
* f49c871 (HEAD -> master, origin/master, origin/HEAD) Update ch01.md (#143)
* ec7b567 Tiep update toc14 (#154)
| * a9c879a (origin/tiep_update_toc14) song ngu
| * 1b073ce update toc
|/
* 8998437 Dịch chương 14 (#140)
* 0fd9e0a update pr template (#153)
| * 49bdede (origin/tiep_udpate_pr_template) update pr template
|/
* d781c32 link to translation PR chap 11 (#151)
* b62448a Tiep update chap 9 (#149)
| * 13fb62f (origin/tiep_translate_chap_11) git cheeckout master -- glossary.md
| * 1291dbc fix typos
| * 87142f9 chap 11, v0
| * fc1790b WIP chap 11
|/
| * 8645d88 (origin/tiep_update_chap_9) song ngu chap 9
| * d5a984e update in toc
|/
```
từ đó bạn biết branch nào gắn với branch nào.

**Comment by freeloneman** [comment]
Để không phải url dài mỗi lần pull, mình làm theo cách sau:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

Như vậy chỉ cần gõ git pull là được phải không bạn?

**Comment by tiepvupsu** [comment]
> Để không phải url dài mỗi lần pull, mình làm theo cách sau:
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
> 
> Như vậy chỉ cần gõ git pull là được phải không bạn?

Mình nghĩ là được, mình chưa thử bao giờ. Bạn thử rồi dùng dòng lệnh này:
```
git log --all --graph --decorate --oneline
```
là sẽ biết đã được cập nhật chưa.

**Comment by seanphan** [comment]
@freeloneman mình cũng bị như bạn. Nếu master của mình behind thì không sao chứ nếu mình nếu có file commit truớc thì làm theo link sẽ add thêm 1 commit là merge từ upstream về master của mình.  

![image](https://user-images.githubusercontent.com/5804000/67624927-7e89ff80-f861-11e9-9130-29aaaea0f1aa.png)

Hiện tại mỗi khi làm chương mới mình sẽ:

```
git checkout master
git reset --hard upstream/master
```

để đảm bảo sync với head ở master (lưu ý, cái này sẽ đè lên hết mấy cái mình làm trên master). xong sau đó branch ra như @tiepvupsu share ở trên

```
git branch bao-chapter3
git checkout bao-chapter3
```
