### ISSUE TITLE
Dịch chương 23

### ISSUE THREAD

**Issue by seanphan** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#174]
Mình nhận dich chương này nha

**Comment by aivivn** [comment]
Chương này @seanphan đã dịch ở https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/pull/175 nhưng không tiếp tục cập nhật. 

Nhóm rất cần một bạn dịch tiếp hoặc dịch lại chương này. Cảm ơn các bạn.

**Comment by seanphan** [comment]
Mình sẽ update tiếp trong hôm nay nha @aivivn
