### ISSUE TITLE
Tiêu đề chương 4 

### ISSUE THREAD

**Issue by anh** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#191]
> Scale drives machine learning progress 

1. _Quy mô thúc đẩy sự tiến bộ trong lĩnh vực machine learning_   

2. _Yêu cầu tăng trưởng về quy mô thúc đẩy sự tiến bộ trong lĩnh vực machine learning_

**Comment by tiepvupsu** [comment]
Mình đã tạo một pull request tại #196, bạn sang bên đó thảo luận nhé.
