### ISSUE TITLE
Thuật ngữ chương 27

### ISSUE THREAD

**Issue by thhung** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#210]
Ở trong chương này có thuật ngữ chưa có trong glossary là dropout. Theo ý mình thì nên giữ nguyên nhưng mình cũng muốn hỏi ý kiến mọi người nên dịch như thế nào cho sát ý nhất trước khi mình thêm vào glossary.

**Comment by tiepvupsu** [comment]
Hiện mình chưa nghĩ ra từ nào tốt hơn. Bạn cứ giữ nguyên, nếu cần phải thay đổi mình có thể đổi sau.
