### ISSUE TITLE
Đề xuất đổi "error" trong một số cụm thành "sai số"

### ISSUE THREAD

**Issue by aivivn** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#230]
Bắt nguồn từ MSE tức "mean squared error", từ này thường được dịch là "sai số trung bình bình phương" (hiện trong cuốn này chúng ta dịch là "lỗi trung bình bình phương") mình đề xuất dịch một số cụm có "error" ra "sai số" thay vì "lỗi"

"training error" -> "sai số huấn luyện"
"dev error" -> "sai số phát triển"

Nếu mọi người đồng thuận, mình nhờ một bạn search hết từ chương 1 tới chương đã được dịch và đổi lại trong một PR.

Chú ý, chỉ sửa trong các file `chapters/chxx.md`, không sửa trực tiếp trên `chapters/all_chapters.md`. File lớn này được tạo bằng cách chạy hàm `main` trong `run.py` để nhóm toàn bộ các chương đã được dịch, không nên sửa trực tiếp.

**Comment by tiepvupsu** [comment]
@sonvx @ngcthuong @william-vu @khoapip @naml3i @xuantubka @phamdinhkhanh, ...

**Comment by william-vu** [comment]
em thì thấy trong MSE dịch là sai số thì hợp lý vì nó là objective function, giá trị liên tục. Còn trong dev error hay training error em cũng chưa rõ nó ám chỉ đến sai số trong MSE hay là sai trong việc nhận dạng một mẫu (phân loại sai). Nếu là sai trong phân loại mẫu thì em vẫn prefer dịch là lỗi.

**Comment by khoangothe** [comment]
> em thì thấy trong MSE dịch là sai số thì hợp lý vì nó là objective function, giá trị liên tục. Còn trong dev error hay training error em cũng chưa rõ nó ám chỉ đến sai số trong MSE hay là sai trong việc nhận dạng một mẫu (phân loại sai). Nếu là sai trong phân loại mẫu thì em vẫn prefer dịch là lỗi.

E thấy đúng thật là sai số dùng để nói về mấy giá trị continuous thì hợp lý hơn là discrete, nhưng mà nếu bài toán theo dạng regression thì lại ngược lại, vì em nghĩ sách nói về machine learning nói chung chứ không chỉ về classification. Em thì thích gọi là sai số hơn, em có tham khảo qua cách dịch chương 29 của anh @phamdinhkhanh thì thấy để là sai số nghe nó smooth hơn.

**Comment by tiepvupsu** [comment]
Mình vừa thử làm một commit trong PR https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/pull/232 để thay toàn bộ các từ "lỗi" thành "sai số" trong cách dịch. Chẳng hạn nếu chúng ta phải thay cụm từ nào thì có thể dùng cách tương tự. Tuy nhiên, những PR kiểu này thường lớn và cần được review kỹ.

**Comment by william-vu** [comment]
cái này hiện tại cứ để mix giữa "sai số" và "lỗi" ở các chương rồi fix sau hả bác Tiệp? @tiepvupsu

**Comment by tiepvupsu** [comment]
Không, có lẽ cần để hai cách dịch khi "error" ở trong các văn cảnh khác nhau. Tuy nhiên, mình phải cụ thể việc này hơn. Em chưa có thời gian lọc hết các trường hợp ra để xem khi nào nên dịch là "lỗi", khi nào nên dịch là "sai số".

Mọi người có thể xem tất cả các trường hợp trong #232

**Comment by tiepvupsu** [comment]
Close since inactive.
