### ISSUE TITLE
Ba chương liền nhau cần được assign cho ba thành viên khác nhau

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#245]
để đảm bảo việc nếu một thành viên có việc đột xuất, chúng ta vẫn có thể tạm bỏ MỘT chương để review các chương tiếp theo.

**Comment by quangnhat185** [comment]
Em cũng kiến nghị là một thành viên sau khi đẩy pull request một chương rồi có thể nhận dịch thêm một chương nữa vì việc đợi review tốn khá nhiều thời gian trong khi việc chỉnh sửa theo review thì lại đơn giản.

**Comment by tiepvupsu** [comment]
> Em cũng kiến nghị là một thành viên sau khi đẩy pull request một chương rồi có thể nhận dịch thêm một chương nữa vì việc đợi review tốn khá nhiều thời gian trong khi việc chỉnh sửa theo review thì lại đơn giản.

Việc này không có xung đột gì với nội dung của issue này. Em vẫn có thể dịch các chương không liền nhau. Ví dụ nếu dịch chương 30 rồi thì chương tiếp theo là một chương LỚN hơn chương 32. Việc này đảm bảo quá trình dịch không bị gián đoạn mấy chương liền nếu một bạn không tiếp tục sửa các PR đã tạo.

Thực ra việc review quan trọng không kém việc dịch, qua việc review mình cũng học được nhiều. Anh nghĩ nếu một bạn dịch chương x thì nên review thêm các chương xung quanh đó để hiểu hơn về cách dịch của mình.

Nhóm không phải không khuyến khích các bạn đóng góp, nhưng hiện tại ít người review hơn số người đóng góp bản dịch, nên bạn nào dịch xong thì qua review các chương khác. Làm đến đâu gọn đến đấy chứ không nên có quá nhiều pending PRs. (Càng nhiều pennding PRs thì càng dễ gây conflict.)
