### ISSUE TITLE
Dịch đồ thị dạng ảnh

### ISSUE THREAD

**Issue by quangnhat185** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#257]
Mình đang dịch chap 28 thì có đồ thị dạng ảnh với chú thích bằng tiếng anh (hình). Trường hợp này mình đề nghị 2 cách để dịch cho mọi người bàn luận:

- Giữ nguyên ảnh gốc và thêm chú thích dạng text ở dưới hình
- Dịch trực tiếp trên đồ thị và save lại dưới dạng ảnh

![C28_01](https://user-images.githubusercontent.com/41325216/68111988-a972f400-fef0-11e9-8e9e-69a685c52e93.png)

**Comment by tiepvupsu** [comment]
Mình thấy xoá tiếng Anh dịch đè lên tiếng Việt hợp lý. Tuy nhiên, nếu chọn hướng này thì cần sửa lại toàn bộ ở các chương liên quan luôn. Bạn làm giúp được không @quangnhat185?

**Comment by quangnhat185** [comment]
> Mình thấy xoá tiếng Anh dịch đè lên tiếng Việt hợp lý. Tuy nhiên, nếu chọn hướng này thì cần sửa lại toàn bộ ở các chương liên quan luôn. Bạn làm giúp được không @quangnhat185?

Được anh, để em làm cho ạ.
