### ISSUE TITLE
Tổng hợp lỗi chính tả + format

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#269]

**Comment by tiepvupsu** [comment]
Nếu bạn gặp một lỗi chính tả hoặc format nào thì thông báo vào trong issue này. Mình sẽ sắp xếp sửa dần, hoặc các bạn có thể trực tiếp sửa bằng cách tạo PRs. Cú pháp thông báo đơn giản như dưới đây:
```
* [ ] In đậm cuối chương 4
```
* [x] In đậm cuối chương 4
(Các lỗi có dấu tick là đã được sửa)
* [x] "khiểu dâm" -> "khiêu dâm"

**Comment by naml3i** [comment]
* [x] Cái này mình không tìm lại được nhưng mình có để ý dấu ngoặc kép của mọi người khác nhau. 
Nó nằm rải rác ở từng chương nếu search all chắc sẽ thấy.

VD như source mình thì mọi thứ được quote nằm giữa 2 dấu ngoặc kép giống nhau: "    "
Tuy nhiên trong source của mọi người, cũng có người có left và right double quotation mark:

"   U+0022 QUOTATION MARK
“   U+201C LEFT DOUBLE QUOTATION MARK
”   U+201D RIGHT DOUBLE QUOTATION MARK

Chắc là do máy, IDE, hoặc text editor khác nhau cái dấu "" mặc định khác nhau. 
Để thống nhất chắc cũng nên convert lại hết thành 1 kiểu :)

**Comment by thanhps** [comment]
* [x] Ở đầu chương 21: "có thẻ" -> "có thể"
"Hãy xem xét việc phân loại mèo của chúng ta. Một bộ phân loại "lý tưởng" (như con người) có thẻ đạt được hiệu suất gần như hoàn hảo cho việc này."

**Comment by tiepvupsu** [comment]
Toàn bộ các lỗi ở trên đã được fixed trong https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/pull/284 rồi nhé.
