### ISSUE TITLE
Một số cách dịch "human-level performance"

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#287]
Hiện có một vài cách dịch cho từ này, chúng ta cần thống nhất một cách dịch cho nhất quán. Vì từ "performance" đã được dịch là "chất lượng" theo #259, mình có vài đề xuất:

* chất lượng cấp con người
* chất lượng mức con người
* chất lượng cấp độ con người
* chất lượng mức độ con người

Mình có một vote cho "chất lượng mức con người". Mọi người nghĩ sao?

@ngcthuong @sonvx @william-vu @honghanhh @thhung @naml3i @lkhphuc @khoapip @patrickphatnguyen @seanphan

**Comment by thhung** [comment]
Em chọn : "chất lượng mức con người" vì theo em thì chữ "độ" là ko cần thiết vì bản thân chữ mức đã bao hàm ý của chữ "độ" rồi. Giữa chữ mức vs chữ "cấp" thì chữ "mức" nghe hợp lý hơn vì theo em thì mức hàm ý "continuous" trong khi đó "cấp" hàm ý "discrete". Trong khi đó thì chất lượng trong trường hợp này là "continous" =>  "chất lượng mức con người" là hợp lý nhất theo ý em.

**Comment by lkhphuc** [comment]
Mình đồng ý chữ "độ" không cần thiết và không hay.
Mình vẫn thích có chữ "ngang/ở" vào giữa hơn.
- "chất lượng _ở_ mức con người"
- "chất lượng _ngang_ cấp con người"
Bản gốc tiếng anh không có từ ghép vì họ có cách tạo từ mới bằng dấu gạch ngang: human-level .
Trong tiếng việt mình ko có kiểu gạch ngang đấy nên bỏ từ "ở / ngang" đi nghe ko hay.

**Comment by lkhphuc** [comment]
Mình đồng ý chữ "độ" không cần thiết và không hay.
Mình vẫn thích có chữ "ngang/ở" vào giữa hơn.
- "chất lượng _ở_ mức con người"
- "chất lượng _ngang_ cấp con người"

**Comment by naml3i** [comment]
- Hoặc nếu dịch thoáng hơn (nghe sẽ tự nhiên hơn) có thể chọn "chất lượng _tương đương_ con người".

- Tuy nhiên nếu chọn trong số các option đã liệt kê (để cố gắng tuân theo cách cấu tạo từ của thuật ngữ gốc, không bị mất đi sắc thái của từ "level") ---> 👍  cho ý "ngang" hoặc "ở" mức con người của @lkhphuc 

Chữ "tương đương" thực ra function chắc cũng từa tựa "ngang cấp"/"ở mức" :D

**Comment by ngcthuong** [comment]
- Từ khóa nên để từ hán-việt cho nó khác với các từ trong câu nên mình chọn "mức". 
- Giữa "người" và "con người" thực ra cũng cùng nghĩa. 
- Không cần thêm "ngang" hay "ở" vì bản chất từ đó đã có nghĩa rồi. Ngang chỉ là trạng thái thôi, còn câu khóa nghĩa là một cột mốc nào đó. 

Mình vote là 
- Chất lượng mức con người 
- Chất lượng mức người

**Comment by william-vu** [comment]
mình thấy "chất lượng mức con người" hoặc là "chất lượng ở mức con người" đều ok.

**Comment by seanphan** [comment]
Mình thấy "chất lượng mức con người" ok nhé.

**Comment by tiepvupsu** [comment]
Theo như mọi người vote ở đây thì mình quyết định chọn "chất lượng mức con người".

Các chương đang ở pending PR cũng dịch theo cụm này luôn nhé cc @honghanhh.
