### ISSUE TITLE
"Dịch" chữ trong các hình có sơ đồ khối từ chương 47

### ISSUE THREAD

**Issue by aivivn** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#327]
Từ chương 47 có rất nhiều sơ đồ khối có chữ ở trong, chúng ta cần dịch các cụm từ trong sơ đồ này.

Ví dụ:
![img](https://i.imgur.com/2XQaj8d.png)

Trước hết có thể liệt kê các cụm cần dịch ra trong issue này, sau đó thống nhất cách dịch trước khi đưa vào hình vẽ.

**Comment by aivivn** [comment]
Đề xuất:

| tiếng Anh | tiếng Việt |
| -- | -- |
| camera images| ảnh từ camera|
| detect cars | dò tìm xe hơi |
| detect pedestrians | dò tìm người đi bộ | 
| plan path for car | hoạch định đường đi cho xe| 
| steering direction| hướng bẻ lái |

**Comment by aivivn** [comment]
@khoapip ^

**Comment by rootonchair** [comment]
Để em giúp phần này nha anh.

**Comment by rootonchair** [comment]
Đề xuất cho chương 47:
`C47_01.png`
![C47_01](https://user-images.githubusercontent.com/23548268/69032008-15377f80-0a0e-11ea-943b-48d7cb3d79a1.png)
`C47_02.png`
![C47_02](https://user-images.githubusercontent.com/23548268/69032016-1b2d6080-0a0e-11ea-8137-de683f798518.png)

| tiếng Anh | tiếng Việt |
| ---            | ---             |
| Original text | Văn bản gốc |
| Annotated text | Văn bản đã chú thích |
| Parser           | Bộ phân tích cú pháp |
| Sentiment Classifier | Bộ phân loại cảm xúc |
| Learning Algorithm | Thuật toán học |
| Output | Đầu ra |

Mình sẽ tiến hành dịch 2 bức ảnh của chương 47 theo cách này nếu không có ý kiến nào.

**Comment by rootonchair** [comment]
Đề xuất chương 48:
`C48_01.png`
![C48_01](https://user-images.githubusercontent.com/23548268/69039554-baf2ea80-0a1e-11ea-9a78-449c4a7636e8.png)
`C48_02.png`
![C48_02](https://user-images.githubusercontent.com/23548268/69039565-bf1f0800-0a1e-11ea-9c4a-d7d1462471bc.png)
`C48_03.png`
![C50_01](https://user-images.githubusercontent.com/23548268/69423745-8736fe00-0d59-11ea-9cc7-f8c2f2a5e0e7.png)
`C48_04.png`
![C48_04](https://user-images.githubusercontent.com/23548268/69039574-c34b2580-0a1e-11ea-8745-27f2b7e2bc65.png)

| Tiếng Anh | Tiếng Việt |
| ---             | ---             |
| Audio        | Âm thanh |
| Compute features | Tính toán đặc trưng |
| Hand-designed MFCC features | Các đặc trưng MFCC thiết kế thủ công |
| Phoneme recognizer | Bộ nhận dạng đơn âm |
| Recognized phonemes | Các đơn âm nhận dạng được |
| Final recognizer | Bộ nhận dạng sau cuối |
| Transcript | Bản ghi thoại |
| Camera image | Hình ảnh từ camera |
| Learning algorithm | (như chương 47) |
| Steering direction | Hướng bẻ lái |
| Detect cars | Phát hiện xe hơi|
| Detect pedestrians | Phát hiện người đi bộ |
| Plan path for car | hoạch định đường đi cho xe |

**Comment by rootonchair** [comment]
@aivivn "detect" ở đây theo em nên dịch là "phát hiện" thì sẽ hợp lý hơn

**Comment by quangnhat185** [comment]
> Đề xuất cho chương 47:
> `C47_01.png`
> ![C47_01](https://user-images.githubusercontent.com/23548268/69032008-15377f80-0a0e-11ea-943b-48d7cb3d79a1.png)
> `C47_02.png`
> ![C47_02](https://user-images.githubusercontent.com/23548268/69032016-1b2d6080-0a0e-11ea-8137-de683f798518.png)
> 
> tiếng Anh	tiếng Việt
> Original text	Văn bản gốc
> Annotated text	Văn bản đã chú thích
> Parser	Bộ phân tích cú pháp
> Sentiment Classifier	Bộ phân loại cảm xúc
> Learning Algorithm	Thuật toán học ~tập~
> Output	Đầu ra
> Mình sẽ tiến hành dịch 2 bức ảnh của chương 47 theo cách này nếu không có ý kiến nào.

Theo [glossary.md][1] thì learning algorithm nên được dịch là thuật toán học cho thống nhất với các chương khác. 

[1]: https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md

**Comment by rootonchair** [comment]
@quangnhat185 mình sẽ edit lại. Thank bạn

**Comment by tiepvupsu** [comment]
@rootonchair Nếu việc dịch và vẽ hình lâu thì mình cứ làm từng chương một -- mỗi chương một PR để không block các bạn khác nhé. Cảm ơn bạn.

**Comment by rootonchair** [comment]
@tiepvupsu Trước mắt em đang chờ thống nhất các cụm được dịch của chương 48. Nếu anh thấy ok thì em tiến hành sửa lại ảnh luôn. Vì nếu chưa thống nhất mà đã sửa ảnh thì sẽ rất mất thời gian để sửa lại.

**Comment by tiepvupsu** [comment]
@rootonchair Anh vừa check lại, anh thấy em làm chương 47 luôn được rồi 

> Đề xuất cho chương 47:
> `C47_01.png`
> ![C47_01](https://user-images.githubusercontent.com/23548268/69032008-15377f80-0a0e-11ea-943b-48d7cb3d79a1.png)
> `C47_02.png`
> ![C47_02](https://user-images.githubusercontent.com/23548268/69032016-1b2d6080-0a0e-11ea-8137-de683f798518.png)
> 
> tiếng Anh	tiếng Việt
> Original text	Văn bản gốc
> Annotated text	Văn bản đã chú thích
> Parser	Bộ phân tích cú pháp
> Sentiment Classifier	Bộ phân loại cảm xúc
> Learning Algorithm	Thuật toán học
> Output	Đầu ra
> Mình sẽ tiến hành dịch 2 bức ảnh của chương 47 theo cách này nếu không có ý kiến nào.

**Comment by rootonchair** [comment]
@tiepvupsu em sẽ PR chương 47 trong tối nay

**Comment by tiepvupsu** [comment]
Chương 48 còn 2 từ:
"recognizer" -> "nhận dạng" như những chương trước. Chữ "diện" có nghĩ là "mặt"

Từ "transcript" anh đang hỏi thêm mấy chỗ làm về NLP xem họ dịch như thế nào.

**Comment by rootonchair** [comment]
Em sẽ edit lại "recognizer" trên comment. Thank anh.

**Comment by tiepvupsu** [comment]
Tiếp tục ở #351.
