### ISSUE TITLE
Dịch "transcript" (danh từ)

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#332]
Hiện đang có những đề xuất khác nhau cho cách dịch từ này: "bản ghi", "bản phiên âm". Anh @sonvx đề xuất một từ là "bản chép lại". Tuy nhiên cả ba từ này mình đều chưa ưng ý lắm.

Trước hết "transcript" trong tiếng Anh có nhiều nghĩa, trong đó có một nghĩa là "bảng điểm". Nghĩa này khác với ý nghĩa của các văn cảnh trong cuốn sách này. Nghĩa thứ hai được sử dụng trong cuốn sách có nghĩa là "bản chuyển đổi từ một đoạn âm thanh ra một đoạn chữ viết". Theo nghĩa này:

* "bản ghi" vẫn còn tối nghĩa.

* "bản phiên âm" mình hiểu là "cách đọc một từ". Ví dụ, phiêm âm tiếng Việt của từ "vector" là vec-tơ.

* "bản chép lại" dễ hiểu là một bản sao.

@ngcthuong @sonvx @rootonchair @khoapip @lkhphuc các bạn thấy thế nào?

**Comment by rootonchair** [comment]
Cả ba đề xuất đúng là chưa được. Em nghĩ thì cũng chỉ ra được một đề xuất là "Bản ghi cuộc hội thoại" nhưng dài quá. "Bản ghi hội thoại" em thấy cũng được nhưng không biết mọi người thấy rõ nghĩa không?

**Comment by tiepvupsu** [comment]
Xem thêm [chương 35](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/chapters/ch35.md) có từ này.

Rất nhiều chương khác cũng có từ "transcription", mình nghĩ có nghĩa tương tự.

**Comment by tiepvupsu** [comment]
Thêm một đề xuất nữa là "bản ghi chép".

Theo từ điển: 
![img](https://i.ibb.co/TTLQRLL/Screen-Shot-2019-11-20-at-8-31-40-AM.png)

thì "transcription" à bản ghi/biểu diễn lại trên giấy của các loại âm thanh.

**Comment by sonvx** [comment]
Mọi người vote theo các emoji tương ứng nhé:
1. "bản ghi" (👍 )
2. "bản gỡ băng" (🎉 )
3. "bản ghi chép" (❤️ )
4. "bản chép lại" (🚀 )
5. "bản ghi thoại" (👀 )
6. "bản ký âm" (😆 )

**Comment by tiepvupsu** [comment]
Anh @sonvx đồng ý với tất cả à? Chọn một cái thôi anh.

**Comment by lkhphuc** [comment]
Mình thích "Bản ghi hội thoại" của @rootonchair.
Chính xác và ngắn hơn nữa có thể là "Bản ghi thoại".
"thoại" tức là lời nời rồi, điện thoại là nói chuyện qua thiết bị điện tử, hội thoại là nói chuyện giữa nhiều người, giai thoại / thần thoại là những câu chuyện truyền miệng, vậy ghi thoại là bản ghi lại lời nói miệng.

**Comment by sonvx** [comment]
> Anh @sonvx đồng ý với tất cả à? Chọn một cái thôi anh.

Anh hy sinh để mọi người có sẵn emoji và tiện vote đấy :D.

**Comment by sonvx** [comment]
> Mình thích "Bản ghi hội thoại" của @rootonchair.
> Chính xác và ngắn hơn nữa có thể là "Bản ghi thoại".
> "thoại" tức là lời nời rồi, điện thoại là nói chuyện qua thiết bị điện tử, hội thoại là nói chuyện giữa nhiều người, giai thoại / thần thoại là những câu chuyện truyền miệng, vậy ghi thoại là bản ghi lại lời nói miệng.

Mình add thêm option "bản ghi thoại" rồi nhé.

**Comment by ngcthuong** [comment]
Mình thấy dịch từ "bản ghi" dễ hiểu nhầm sang ý "records". Mang theo hàm ý copy thì có từ "sao", "chép". Nếu gộp lại ý đầu như của Tiệp nói thì có thể có thêm một số gợi ý là

- Bản chép thoại
- Bản sao thoại. 
- **Bản phiên thoại.** 

Từ Transcription trong sinh học trước đó dịch là sao mã nhưng đã được thống nhất lại là dịch là Phiên mã. Nên có vẻ ý cuối hợp lý hơn. 

https://vi.wikipedia.org/wiki/Phi%C3%AAn_m%C3%A3

**Comment by tiepvupsu** [comment]
Hay vãi. Từ "phiên thoại" nghe lạ nhưng để nó so sánh với "phiên âm" thì lại khá xứng!

**Comment by tiepvupsu** [comment]
Vừa có thêm một đề xuất trên facebook anh @sonvx nữa: "bản ký âm". Mình lại đổi gió thích từ này.

"Bản ký âm" có nghĩa là ghi chép lại tín hiệu âm thanh ra giấy. Nó không nhất thiết là tín hiệu "thoại" mà là tín hiệu "âm" nói chung. Các bản nhạc mà nhạc sĩ viết ra cũng là "transcription", chắc chắn không thể dùng "thoại" cho nhạc không lời được.

**Comment by rootonchair** [comment]
"ký âm" thường để chỉ những bản nhạc/nốt nhạc được viết trên giấy và được sử dụng nhiều trong lĩnh vực âm nhạc. Nếu mình sử dụng sẽ bị sẽ bị nhầm lẫn với định nghĩa trên nên em không ủng hộ cách dịch là "bản ký âm" cho lắm

**Comment by rootonchair** [comment]
Em có tìm hiểu thì "transcript" theo [từ điển Cambridge](https://dictionary.cambridge.org/vi/dictionary/english/transcript) là:

> a complete written copy of spoken or written words

Ngoài ra, "audio transcription" theo https://www.universitytranscriptions.co.uk/the-definition-of-audio-transcription/ là:

> **Audio transcription is the notation in writing or symbols of a sound file of some sort, whether this is analogue or digital. It is usually used in the context of a recording of a human’s voice or voices**, and is used also in the context of the business of transcription, which is to notate a sound recording and turn the sounds into words or words that describe sound effects.

> **Most audio transcription is a notation or record of an audio recording of one or more human voices speaking or communicating with each other**. However transcription is also used to notate sounds when, for example, two animals communicate with each other.

Nên em nghĩ "bản ghi thoại" sẽ là từ phù hợp. "bản ghi" không sợ hiểu nhầm là "record" vì từ này trong tiếng Anh có thể được hiểu theo nghĩa "một văn bản lưu lại thông tin".

Dù sao, một vài trang tiếng Việt không dịch từ này mà để nguyên là "transcript". Đây cũng có thể là một lựa chọn.

**Comment by tiepvupsu** [comment]
Ok mọi người, vậy nếu không ai có thêm ý kiến thì mình sẽ chọn "bản ghi thoại".

Bạn nào xung phong làm một PR để đổi lại các chương đã được dịch không?

**Comment by tiepvupsu** [comment]
Theo vote phía trên mình sẽ chọn "bản ghi thoại", sau đó sẽ làm một PR để đổi toàn bộ từ đầu.
