### ISSUE TITLE
Dịch từ "pipeline"

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#334]
Không phải là "đường ống nước" nhé.

Có bạn đang dịch là "chuỗi thuật toán". Cụm này khá gần nhưng mình vẫn chưa thấy chuẩn.
Theo mình thì từ "chu trình" có vể gần hơn nhưng không chắc chắn lắm.

Có thể tham khảo thêm ML pipeline [tại đây](https://towardsdatascience.com/not-yet-another-article-on-machine-learning-e67f8812ba86):
> ML Pipeline
> Data scientists define a pipeline for data as it flows through their ML solution. Each step of the pipeline is fed data processed from its preceding step. The term ‘pipeline’ is slightly misleading as it implies a one-way flow of data; instead the ML pipelines are cyclical and iterative as every step is repeated to finally achieve a successful algorithm.

**Comment by tiepvupsu** [comment]
Mình vừa vào xem lại phần thảo luận của nhóm dịch Deep Learning (phần này kín nên mình không có link share) thì `pipeline` được giữ nguyên sau khi không tìm được từ nào tương xứng.

Còn cụm "end-to-end" bên đó dịch là "đầu-cuối". "Pipeline" là một chuỗi các thuật toán được kết nối với nhau để tạo thành một hệ thống hoàn chỉnh. "End-to-end Pipeline" là "pipeline đầu-cuối" hay "end-to-end model" tức "mô hình đầu-cuối", chỉ một hệ thống (học máy) bao gồm toàn bộ các bước được học trong một thuật toán duy nhất.

Mình thấy để thế này cũng ok. Dùng nhiều mọi người sẽ quen.

**Comment by ngcthuong** [comment]
Dịch end-to-end thành đầu cuối nghe có vẻ OK nhưng có thể bị nhầm với khái niệm "end user", "end node", "end equipment" với từ **_end_** được hiểu là **thiết bị ở đầu cuối cùng**.

**Comment by tiepvupsu** [comment]
@ngcthuong có dấu gạch ngang ở giữa nên sẽ hiểu nó là một tính từ.

**Comment by ngcthuong** [comment]
Nếu để có dấu gạch giữa nối vậy cho "đầu-cuối" có vẻ hợp lý, cũng không bị nhầm. Mà từ gạch ngang để ám chỉ cụm danh từ mà nhỉ. 

Về từ Pipleline, có nguồn dịch thông thường là "luồng" nữa. Ví dụ như hình dưới. 

![image](https://user-images.githubusercontent.com/6524339/69298631-d6920700-0c51-11ea-943f-057f57b29fd7.png)

**Comment by tiepvupsu** [comment]
Từ "luồng" hay vãi mặc dù mình chưa hiểu lắm.

> Nếu để có dấu gạch giữa nối vậy cho "đầu-cuối" có vẻ hợp lý, cũng không bị nhầm. Mà từ gạch ngang để ám chỉ cụm danh từ mà nhỉ.

Cái gạch ngang là cụm danh từ là ở đâu ra nhỉ? Trong tiếng Việt có quy tắc này à cậu? Tiếng Anh thì nó có thể thuộc nhiều từ loại.

**Comment by ngcthuong** [comment]
Hmm. Chắc mình hơi bị nhầm lẫn một chút. Mình cần làm rõ lại đấu gạch kia là "gạch ngang" hay "gạch nối". 

- Gạch ngang trong tiếng Việt mang ý chỉ giải thích vế phải. Khá giống tiếng Anh. 
- Gạch nối trong tiếng Việt mang ý chỉ cách phiên âm từ Quốc tế sang tiếng Việt. 

Tớ nghĩ trường hợp này là dấu "gạch nối". 

Trường hợp mấy từ gạch nối trong tiếng anh ví dụ như **_You-Know-Who_** được dịch là "Kẻ mà ai cũng biết" trong Harry Porter. Không có dấu gạch ngang mà để trong dấu nháy kép. 


https://baodanang.vn/channel/6059/201501/dau-gach-ngang-va-dau-gach-noi-2391622/

**Comment by quangnhat185** [comment]
Hiên tại ở chương 47 #336  em đang giữ nguyên "pipeline" và dịch "end-to-end" là "đầu cuối". Mọi người thống nhất được về hai thuật ngữ này thì báo em biết để em sửa lại.

**Comment by tiepvupsu** [comment]
@quangnhat185 từ pipepline em cứ giữ nguyên nhé. Từ "luồng" dễ bị nhầm trong văn cảnh "đa luồng" (multithreads) nên anh chưa ưng.

Còn từ "đầu-cuối" em cứ thêm gạch ngang vào để phân biệt với "đằng cuối".

**Comment by tiepvupsu** [comment]
> Hmm. Chắc mình hơi bị nhầm lẫn một chút. Mình cần làm rõ lại đấu gạch kia là "gạch ngang" hay "gạch nối".
> 
> * Gạch ngang trong tiếng Việt mang ý chỉ giải thích vế phải. Khá giống tiếng Anh.
> * Gạch nối trong tiếng Việt mang ý chỉ cách phiên âm từ Quốc tế sang tiếng Việt.
> 
> Tớ nghĩ trường hợp này là dấu "gạch nối".
> 
> Trường hợp mấy từ gạch nối trong tiếng anh ví dụ như **_You-Know-Who_** được dịch là "Kẻ mà ai cũng biết" trong Harry Porter. Không có dấu gạch ngang mà để trong dấu nháy kép.
> 
> https://baodanang.vn/channel/6059/201501/dau-gach-ngang-va-dau-gach-noi-2391622/

Chỗ đó mình dùng gạch nối, tức một dấu gạch không có dấu cách xung quanh. Gạch ngang là hai dấu gạch (trong markown) có dấu cách hai bên.

Từ "đầu-cuối" có dấu gạch nối để phân biệt với "đầu cuối" có nghĩa là "đằng cuối" hoặc "phía cuối". hơn nữa, dấu gạch nối ở đây cũng có nghĩa thay thế từ "to" trong tiếng Anh. Ví dụ, "5 đến 7" cũng được viết là "5-7" trong tiếng Việt.

Mình sẽ thêm từ này vào trong glossary bây giờ:

* pipeline: pipeline
* end-to-end: đầu-cuối

**Comment by nmdang** [comment]
mình đọc qua mấy chương cuối, thấy có vẻ tác giả sử dụng ```end-to-end pipeline``` để phân biệt với một pipeline gồm nhiều tasks/subtasks. Như vậy phần nào một ```end-to-end pipeline``` tương đương với một ```single-task (single component) pipeline```. Nên chăng ta dịch ```end-to-end``` thành ```đơn tác vụ``` cho rõ ý tác giả? 

Ngoài ra mình nghĩ pipeline có thể dịch thành ```chuỗi tác vụ``` e.g. machine learning pipeline --> chuỗi tác vụ học máy

**Comment by tiepvupsu** [comment]
@nmdang `Pipeline` nghĩa sử dụng thông thường là `hệ thống ống dẫn nước`, nó thể hiện sự kết nối giữa nhiều thành phần trong hệ thống với nhau. Hệ thống này có thể có nhiều đầu vào, nhiều đầu ra, các khối liên hệ với nhau không nhất thiết theo dạng `nối tiếp`mà còn có cả các đoạn nối `song song` nữa.

Mình nghĩ `chuỗi tác vụ` chỉ là bao gồm một tập con của `pipeline`. Từ `chuỗi` mới chỉ đặc tả được phần `nối tiếp` (`sequential`) mà chưa mô tả được các kết nối phức tạp hơn.

Đây là ý hiểu của mình. Chúng ta có thể bàn luận thêm.

> Nên chăng ta dịch `end-to-end` thành `đơn tác vụ` cho rõ ý tác giả?

Ý bạn là `end-to-end pipeline` dịch thành `đơn tác vụ`? Theo mình hiểu thì `single-task` hay `single-component` không mô tả hết ý được `end-to-end pipeline`, vì nếu được thì có lẽ trong tiếng Anh người ta đã dùng `single task` luôn thay vì phải mượn từ `pipeline` có tính tượng hình từ ngôn ngữ thông thường.

**Comment by nmdang** [comment]
Đúng là từ ```chuỗi``` không miêu tả hết ý của ```pipeline``` thật, tỉ dụ như trong chapter 48. Ý kiến bản thân thì không thích từ pipeline lắm, nhưng cũng không biết cách dịch nào trọn vẹn. 

thực ra mình định đề xuất ```end-to-end pipeline``` dịch thành ```pipeline đơn tác vụ```, nghĩa là vẫn giữ nguyên từ pipeline, hoặc thay bằng một từ dịch tương ứng

**Comment by thhung** [comment]
Em vote cho ý để giữ nguyên pipeline có gắn thêm giải thích vì từ này thật ra khó có thể dịch chuẩn được và bao hàm toàn bộ ý của nó. Sau này, khi mình có thể tìm được từ nào tốt hơn, mình có thể thay sau.

**Comment by tiepvupsu** [comment]
Mình đã quyết định giữ nguyên từ pipeline.
