### ISSUE TITLE
"Mạng neural" -> "Mạng neuron" hoặc "Mạng nơ-ron"

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#335]
Mình nghĩ kỹ lại thì từ "neural" có là một tính từ, nếu đổi ra tiếng Việt thì cần một danh từ thế vào đó.

Danh từ của "neural" là "neuron" nên mình đề xuất là "mạng neuron".

Còn "mạng nơ-ron" là cách đọc từ ngày trước của các cụ. Các cụ thích phiên âm ra nên đọc vừa khó hiểu vừa khó biết từ gốc là gì. Nếu có từ Việt hẳn thì để, không thì dùng luôn từ tiếng Anh.

Mọi người vote nhé:

* "neural network" (giữ nguyên) (👍 )
* "mạng nơ-ron" (🎉 )
* "mạng neural" (❤️ )
* "mạng neuron" (🚀 )

Mình vote hết để mọi người chỉ cần click. Mình chọn "mạng neuron" nếu đến cuối cần cộng vào.

**Comment by ngcthuong** [comment]
Mình có google qua một lượt các kết quả. Dùng "neural network" thì dùng hơi nhiều tiếng Anh trong khi từ network là từ phổ thông. Từ "mạng neuron" thì gần như không có ai dùng cả. Nếu chỉ mình viết theo kiểu này thì hơi kỳ. 

Về ý kiến cá nhân, nếu muốn để chuẩn hóa tiếng Việt giống như "Học máy". Để là "Mạng nơ-ron" là hoàn toàn ổn. Vì ai cũng hiểu mình nói tới cái gì. Và từ này cũng dùng khá thông dụng. 

Nên mình sẽ vote cho cả hai: Mạng nơ-ron và mạng neural. Tuy nhiên mình thiên về mạng Nơ-ron hơn vì số lượng tìm kiếm lớn hơn. 

![image](https://user-images.githubusercontent.com/6524339/69298928-9da66200-0c52-11ea-87bb-0b7c1e848e92.png)

![image](https://user-images.githubusercontent.com/6524339/69298941-a7c86080-0c52-11ea-83e8-4298a8abb052.png)

**Comment by rootonchair** [comment]
![image2](https://user-images.githubusercontent.com/23548268/69324311-ce9a8d00-0c7a-11ea-94ca-852370cb3c00.jpg)
![book](https://user-images.githubusercontent.com/23548268/69324330-d78b5e80-0c7a-11ea-899b-be2d6f157f9b.jpg)



Trong cuốn "Deep learning, cuộc cách mạng học sâu" của Thái Hà Books sử dụng cách dịch là "mạng nơ-ron", em nghĩ mình cũng nên sử dụng cách dịch này.

**Comment by tiepvupsu** [comment]
Ok, mình sẽ thay bằng "mạng nơ-ron". Dấu gạch nối có hai tác dụng:

* Thể hiện đây là cách phiên âm 
* Thể gõ tiếng Việt không bị lỗi. Không có dấu gạch nối gõ nhanh nó sẽ thành "nổn" :D.
