### ISSUE TITLE
Dịch chữ trong hình từ chương 51 đến 57

### ISSUE THREAD

**Issue by rootonchair** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#351]
Từ chương 51 trở về sau có những từ mới sau:

| Tiếng Anh | Tiếng Việt| Tại chương |
| --- | --- | --- |
| Siamese cat classifier | Bộ phân loại mèo Siamese | 51 |
| Cat detector | Bộ phát hiện mèo | 51 |
| Cat breed classifier | Bộ phân loại giống mèo | 51 |
| Detect lane markings | Phát hiện vạch kẻ đường | 57 |

@tiepvupsu các từ này khá đơn giản nhưng anh giúp em check qua thử xem có đồng bộ với các bản dịch không nhé.

**Comment by tiepvupsu** [comment]
Chỗ classifier em đổi là "phân loại" nhé.
Từ "nhận dạng" mình dùng cho "recognizer"
