### ISSUE TITLE
Dịch "bounding box" ở chương 54

### ISSUE THREAD

**Issue by quangnhat185** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#353]
Hiện tại mình đang dịch chương 54 #352 thì có từ "bounding box" mình vẫn giữ nguyên vì nếu dịch ra  là "hộp viền" thì hơi thô. Không biết ý kiến mọi người thế nào?

**Comment by tiepvupsu** [comment]
Anh nghĩ từ "box" ở đây có thể dịch là "khung", như vậy sẽ sát với ý nghĩa của "bounding box"  hơn. Còn từ "bounding" thì có thể dịch là "chứa" hoặc "bao quanh".

Mình vote cho "khung chứa".

@sonvx @naml3i @rootonchair @naml3i @honghanhh @ngcthuong và các bạn khác vào đưa đề xuất và vote nhé.

**Comment by rootonchair** [comment]
Em thấy đề xuất "khung chứa" phù hợp

**Comment by quangnhat185** [comment]
Em vote cho "khung chứa".

**Comment by tiepvupsu** [comment]
Ok, vậy mình chọn "khung chứa" nhé. @quangnhat185 tạo nhanh một PR riêng được không? Đồng thời em cũng đổi luôn các từ "bounding box" trong chương em đang dịch.

**Comment by Khiem179** [comment]
Có thể thêm một phương án khác là 'khung bao ngoài' được không?
