### ISSUE TITLE
Cách gợi ý thay đổi trực tiếp vào Pull Request

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#370]
Mình mới học được một điều thú vị từ bạn @nmdang về các gợi ý thay đổi trực tiếp trong pull request.

Thay vì dùng `~~xóa chữ~~` hay `_thêm chữ_`, chúng ta có thể trực tiếp đề xuất thay đổi trong `suggestion` như trong [hướng dẫn này](https://haacked.com/archive/2019/06/03/suggested-changes/).

Khi đó các tài khoản tạo PR chỉ cần click vào "commit suggestion" là thay đổi sẽ trực tiếp được đưa vào PR, ko cần tự sửa lại bằng tay nữa.

Dưới đây là ảnh minh họa:
![img](https://i.ibb.co/j4y7mD4/Screen-Shot-2019-11-26-at-9-59-48-AM.png)

**Comment by quangnhat185** [comment]
Chức năng này tiện thật tiếc là gần hết sách rồi mới biết. Thôi thì đợi dự án tiếp theo xài vậy :smile:

**Comment by tiepvupsu** [comment]
@quangnhat185 dự án tiếp theo dự tính kéo dài nửa năm, tha hồ mà xài nha.
