### ISSUE TITLE
Tạo file pdf cho bản đầy đủ 

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#376]
Mục đích: tạo hai file pdf cho bản song ngữ và bản chỉ tiếng Việt.

Yêu cầu:
* [ ] Có thể viết thêm code hoặc dùng các phần mềm miễn phí.
* [ ] chỉ dùng một dòng lệnh để cập nhật bản pdf sau khi có sửa đổi.

Tham khảo: [How Can I Convert Github-Flavored Markdown To A PDF](https://superuser.com/questions/689056/how-can-i-convert-github-flavored-markdown-to-a-pdf)

**Comment by quangnhat185** [comment]
Em xin nhận task này nhé.

**Comment by tiepvupsu** [comment]
@quangnhat185 nhớ đảm bảo hai yêu cầu nhé em!
