### ISSUE TITLE
Tách glossary ra một repository riêng

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#378]
Đây là một dự án này tương đối là thành công khi thu hút được đóng góp của rất nhiều thành viên. Chất lượng các bản dịch và review tăng dần ở cuối giai đoạn một. Các milestones đặt ra đều được thực hiện đúng và thậm chí trước thời hạn. Mình rất mong dự án này có thể nhân rộng cho các cuốn sách khác. Chúng ta có thể tạo một quy trình tốt để các dự án sau này được thực hiện một cách hiệu quả hơn.

Một trong những thành công của dự án này là có được bảng thuật ngữ Anh-Việt tương đối với khoảng vài trăm từ. Khi dịch các tài liệu khác, chúng ta nên bám vào bảng thuật ngữ này để dịch cho nhất quán, người đọc khi tiếp xúc nhiều cũng sẽ dần quen với cách dịch. Nếu họ tiếp tục sử dụng các thuật ngữ này, chúng ta sẽ có một bộ tài liệu tiếng Việt dồi dào và thống nhất. Đó là mục đích to lớn mà mình mong một dự án tương tự như thế này có thể đạt được.

Việc xây dựng một bảng thuật ngữ chung nên được tách riêng ra một dự án (Github repository) khác để tạo chuẩn cho các tài liệu về sau (chúng ta sẽ chuẩn bị dịch cuốn https://www.d2l.ai/). Sau khi dịch cuốn thứ hai này, dự kiến chúng ta có được khoảng một (vài) nghìn thuật ngữ _được thảo luận kỹ và sử dụng một cách nhất quán_. Khi xây dựng bảng thuật ngữ này, chúng ta có thể thêm định nghĩa và văn cảnh mà mỗi từ được sử dụng.

Mời các bạn tham gia thảo luận việc xây dựng bản thuật ngữ chung này.

**Comment by thhung** [comment]
Em hoàn toàn đống ý với ý kiến này. Việc thống nhất về khái niệm giữa các bản dịch là rất quan trọng. Nhớ lại thời sinh viên đọc sách của mỗi thầy là 1 cụm từ khác nhau cho chung 1 khái niệm thực sự rất mất thời gian cho việc học.

**Comment by ngcthuong** [comment]
Mình hoàn toàn đồng ý đề nghị này ngay từ lúc bắt đầu project. Cần thêm cả ví dụ và trích đoạn từ các quyển sách khác để giải thích ý nghĩa chuẩn xác hơn.

**Comment by tiepvupsu** [comment]
Hiện việc phải quản lý nhiều repo một lúc sẽ phức tạp hơn một chút. Mình chờ d2l-vn xong sẽ tách glossary riêng ra.
