### ISSUE TITLE
Dịch "gradient descent"

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#389]
Cụm này đang được dịch là "hạ dốc" trong glossary. Theo mình từ "dốc" ở đây không lột tả được bản chất toán học của cụm tiếng Anh. "Gradient" là một khái niệm toán học quan trọng đã được sử dụng nhiều ở Việt Nam:
https://vi.wikipedia.org/wiki/Gradien

Theo mình nên giữ lại từ "Gradient" hoặc "Gradien", có thể dịch thành:

1) Hạ Gradient
2) Trượt Gradient
3) Hạ Gradien
4) Trượt Gradien

Các phiên âm thành "Gradien" hay "vec-tơ" là cách phiên âm trước đây cho dân mình dễ đọc, theo mình nếu không dịch được thì nên giữ lại nguyên từ gốc để tránh nhầm lẫn. 

Mong các bạn thảo luận thêm.

**Comment by nmdang** [comment]
Khái niệm này là khá quan trọng, có lẽ mình nên tham vấn xem ở các trường đại học dạy thế nào để dùng cho đồng nhất.

Một cách dịch nữa có thể là "Phương pháp Gradient" (xem thêm phần các kỹ thuật tại: https://vi.wikipedia.org/wiki/T%E1%BB%91i_%C6%B0u_h%C3%B3a_(to%C3%A1n_h%E1%BB%8Dc). Từ này cũng sát với nghĩa tiếng Pháp (L'algorithme du gradient) khi Cauchy viết. 

Hoặc bạn nào ở Việt Nam có thể tra cứu giùm cuốn "Lý thuyết tối ưu và đồ thị" - Doãn Tam Hòe xem tác giả viết sao?

**Comment by nmdang** [comment]
Một số luận văn toán ghi là "Thuật toán chiếu dưới đạo hàm"

**Comment by khoangothe** [comment]
Em nghĩ hạ Gradient hay hạ Gradien đều được ạ, nhưng mà em thích hạ Gradient hơn, vì nếu dịch để phiên âm theo tiếng việt thì Gradient hay Gradien cũng không khác nhau lắm. Trượt Gradient thì em nghĩ không nên lắm tại vì nếu sau này dịch "gradient ascend" sẽ khó.

**Comment by thhung** [comment]
Em vote cho Hạ Gradien vì 2 lý do:
- Hạ thì tốt hơn trượt, thể hiện rõ mục đích giảm loss dựa vào gradient, trượt gợi ý về tính liên tục hơn. 
- Gradien tốt hơn gradient vì mọi người đã quen khái niêm này rồi, ko cần thiết phải chọn gradient, có thể sẽ tạo nhiều confusion hơn.

**Comment by lkhphuc** [comment]
Cùng ý @khoapip @thhung . Mình vote cho "Hạ Gradient".
Sẵn đây mình bàn luôn nếu sách sau này có xài, thì "gradient ascent"  dịch là "Nâng Gradient" được không?

**Comment by tiepvupsu** [comment]
Okay, vậy giờ còn hai lựa chọn:

1) Hạ gradien
2) Hạ gradient

Mình ủng hộ (2) vì mình nghĩ nếu không dịch được thì nên giữ nguyên từ gốc để tránh việc phiên âm bị sai.

Cả các từ vec-tơ, nơ-ron mình cũng ủng hộ việc giữ nguyên tiếng Anh là vector và neuron.

**Comment by phamdinhkhanh** [comment]
em vote 2 vì nếu như chưa biêt tiếng anh mà đọc từ `gradien` cũng không hiểu. Vậy thì đối với người mới `gradien` và `gradient` về bản chất đều không phải là âm tiếng việt. Do đó giữ gradient để khi search google còn ra cách giải thích của nó. Không những TH này mà với nhiều thuật ngữ tiếng anh chưa được dịch ra tiếng việt khác.

**Comment by tiepvupsu** [comment]
Ok, vậy mình sẽ thống nhất lấy "hạ gradient"
