### ISSUE TITLE
Dịch "detector"

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#390]
Hiện có hai cách dịch cho từ này:
1) Bộ phát hiện
2) Bộ dò tìm

Cách (1) đang được sử dụng chủ yếu trong các chương đã dịch. Cách (2) liên quan đến cách dịch "detect" ra "tìm" như bạn @nmdang đề xuất.

Mời các bạn thảo luận thêm.

**Comment by thhung** [comment]
Em thấy bộ phát hiện hợp lý hơn, bộ dò tìm hàm ý rằng thuật toán này scan toàn bô ảnh để chỉ ra vị trí của vật thể (hoàn toàn đúng cho các thuât toán hiện tại nhưng chưa chắc đã đúng cho các thuật toán trong tương lai) trong khi bản chất của bài toán là phát hiện vị trí của vật thể. 

p/s: Thực ra cả 2 ý cách dịch đều đúng, tùy vào góc nhìn nhưng cách dịch 1 tổng quát hơn.

**Comment by tiepvupsu** [comment]
Mình thấy hai từ này không khác nhau nhiều. Xét đến khía cạnh nhất quán trong cách dịch, khi dịch từ "detector" chúng ta cũng cần quan tâm đến các từ "detection" và "detect":

* "object detection" thành "dò tìm vật thể" hay "phát hiện vật thể".
* "detect cars" thành "phát hiện xe" hay "dò tìm xe".

Mình đã tạo #396 để đổi các chỗ đã được dịch thành "phát hiện" sang "dò tìm" (chưa merge). Sau khi tạo PR này và đọc lại các đoạn được sửa đổi, mình lại thấy rằng từ "phát hiện" hợp lý hơn.

cc @nmdang @ngcthuong @naml3i 

@rootonchair em đừng đổi "detect car" vội. Anh thấy vấn đề này cần thảo luận kỹ hơn.

**Comment by rootonchair** [comment]
Từ "phát hiện" là cách dịch phù hợp trong đa số ngữ cảnh. Em đề xuất giữ "detector" là "bộ phát hiện". Riêng "detect" mình có thể sử dụng "phát hiện" và "dò tìm" thay phiên nhau tùy theo bối cảnh và độ trôi chảy cho đoạn văn.

**Comment by aivivn** [comment]
@rootonchair ok, anh cũng nghĩ là sẽ giữ lại "bộ phát hiện" cho "detector", còn "detect" thì tùy văn cảnh. cc @nmdang.
