### ISSUE TITLE
Dịch "underfitting", "fitting", "overfitting"

### ISSUE THREAD

**Issue by rootonchair** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#391]
Trong chương 21 có câu:
> We say that this algorithm is **underfitting**.

Được dịch là:
"Chúng ta nói thuật toán này là **underfitting**"

Mình đề xuất dịch lại thành:
"Chúng ta nói thuật toán này đang **underfit**"

Không biết mọi người thấy sao

Nhân tiện đây, @tiepvupsu em thấy #87 vẫn chưa hoàn thành việc dịch (vẫn để nguyên tiếng Anh) những từ như:

| Tiếng Anh | Tiếng Việt (đề xuất từ #87 ) |
| :---: | :---: |
| fit | khớp |
| overfit | quá khớp |
| underfit | vị khớp |

**Comment by aivivn** [comment]
Mình thấy "khớp" và "quá khớp" khá ok, nhưng "vị khớp" thì chưa hiểu ý của từ đó lắm. Bạn có ví dụ nào về từ "vị" dùng theo nghĩa "unber" không?

**Comment by ngcthuong** [comment]
Những từ hợp với nghĩa underfit
- hạ khớp (nhưng hạ cũng là động từ)
- thiếu khớp ( giống như thiếu niên)
- dưới khớp (như ở phía dưới, thấp hơn) 
- vị khớp (trong vị thành niên) 

Nghe qua thì thấy từ "thiếu" với "vị" có vẻ ok. Từ vị thì nghe nó lạ vì mọi người ít dùng hơn từ thiếu.

Còn anh em ngồi nói chuyện vui với nhau thì nên dùng từ chuẩn là "thấp khớp"

**Comment by rootonchair** [comment]
Em nghĩ chúng ta cần bàn luận cách dịch của underfit.

**Comment by tiepvupsu** [comment]
Mình nghĩ qua nay mà vẫn không tiêu hóa được từ "vị khớp". Để là "chưa khớp" dễ hiểu hơn chứ nhỉ.

**Comment by rootonchair** [comment]
Em vote cho từ "dưới khớp". Từ "chưa khớp" phần nào đó quá thông dụng nên có thể khi đọc không nhận ra là thuật ngữ.

**Comment by tiepvupsu** [comment]
Anh cũng vote cho "dưới khớp".

**Comment by tiepvupsu** [comment]
https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/pull/415#issuecomment-561523546

**Comment by tiepvupsu** [comment]
@rootonchair issue này nhé.

**Comment by rootonchair** [comment]
@tiepvupsu anh muốn bắt đầu khi xong revise đợt 2 hay thay luôn bây giờ?

**Comment by tiepvupsu** [comment]
Luôn em ạ.

**Comment by rootonchair** [comment]
Tối em sẽ có PR
