### ISSUE TITLE
Dịch tên sách "Machine Learning Yearning"

### ISSUE THREAD

**Issue by aivivn** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#394]
Mời các bạn đề xuất cách dịch tên cuốn sách này.

**Comment by lkhphuc** [comment]
"Khát Khao Học Máy"

**Comment by rootonchair** [comment]
> "Khát Khao Học Máy"

"Khát khao Học Máy"
Để từ "học" không bị hiểu nhầm là động từ
