### ISSUE TITLE
Dự án chị em

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#398]
Mình thấy dự án hiện tại rất thành công. Cảm ơn các bạn đã đóng góp công sức để dự án có được kết quả như hiện tại. Chúng ta sẽ hoàn thiện các issue còn lại trong vòng 2 tuần nữa và công bố bản pdf cuối cùng!

Mình rất mong muốn những bạn đã tham gia dự án này tiếp tục tham gia một dự án lớn hơn và thú vị hơn:

https://d2l.aivivn.com/intro_vn.html

Các bạn có thể tham gia slack thảo luận bằng cách đăng ký form này:
https://docs.google.com/forms/d/e/1FAIpQLScYforPRBn0oDhqSV_zTpzkxCAf0F7Cke13QS2tqXrJ8LxisQ/viewform

**Comment by goldenretriever2015** [comment]
@tiepvupsu  Mình hỏi xíu việc đăng ký form này và việc đóng góp trực tiếp vào dự án d2l qua pull request thì có gì khác không bạn?

**Comment by tiepvupsu** [comment]
> @tiepvupsu Mình hỏi xíu việc đăng ký form này và việc đóng góp trực tiếp vào dự án d2l qua pull request thì có gì khác không bạn?

Bạn hoàn toàn có thể tạo Pull Request trực tiếp từ repo mà không cần đăng ký form. Bạn chỉ cần đăng ký form nếu muốn giao lưu và thảo luận kỹ hơn với mọi người.
