### ISSUE TITLE
Lưu ý về đẩy nhanh tiến độ dịch giai đoạn 2 "Revise" 

### ISSUE THREAD

**Issue by ngcthuong** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#425]
Sau giai đoạn 1 dịch sát nghĩa đã hoàn thành thì giai đoạn 2 cũng bắt đầu bằng việc nhóm 3-4 chương lại với mục tiêu là 

- Thống nhất từ ngữ dịch và giọng văn giữa các chương. 
- Sửa các lỗi diễn đạt và câu dịch còn hơi "Google". 

Vì thời gian chỉnh sửa cả 3-4 chương cùng lúc là rất dài kể cả cho người "revise" lấn người review, đồng thời tiến độ hoàn thiện Phase 2 trong năm 2019 này (năm mới qua quyển mới dịch thôi), nên mình có một số đề nghị như sau 
- Dùng công cụ "suggestion" để gợi ý chỉnh sửa thay vì chỉ comments 
- Không cần dịch "quá hay" và "quá mượt". Chỉ cần đọc hiểu đúng và thống nhất các chương như mục tiêu bên trên là ổn. 
- Có thể bỏ qua các lỗi lắt nhắt, nhỏ lẻ

Mọi người có đóng góp gì thêm để đẩy nhanh tiến độ không nhỉ? 
@nmdang @seanphan  @tiepvupsu @naml3i  @rootonchair @lkhphuc

**Comment by rootonchair** [comment]
Em đồng ý với những điều trên. Em có một gợi ý nữa là (nếu được) cung cấp 1 bản tiếng Việt của các chương sẽ revise. Trong lúc đọc, em thường bị gián đoạn bởi những câu tiếng Anh bên trên bản dịch. Nếu tách ra mình sẽ dễ đọc và đánh giá trên toàn chương hơn là những đoạn nhỏ lẻ. Nếu cần check nghĩa và sửa thì có thể quay lại bản gốc riêng. 

Không biết anh Tiệp có code để gen bản tiếng Việt cho một chap không?

**Comment by tiepvupsu** [comment]
> Không biết anh Tiệp có code để gen bản tiếng Việt cho một chap không?

Hiện có code để gen bản tiếng Việt cho toàn bộ các chương. Việc tạo bản tiếng Việt cho từng chương cũng không khó vì bản chất của file toàn bộ chương là gộp từng chương nhỏ lẻ lại.

Anh thấy em có thể trực tiếp xem file chỉ tiếng Việt này lúc revise https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/chapters/all_chapters_vietnamese_only.md#21-nh%E1%BB%AFng-v%C3%AD-d%E1%BB%A5-v%E1%BB%81-%C4%91%E1%BB%99-ch%E1%BB%87ch-v%C3%A0-ph%C6%B0%C6%A1ng-sai

File này có link tới từng chương ở phần mục lục nên cũng khá tiện.

**Comment by rootonchair** [comment]
Em sẽ làm vậy. Cảm ơn anh
