### ISSUE TITLE
Dấu phẩy thập phân chương 16

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#426]
Hiện tại đang là dấu chấm.

**Comment by rootonchair** [comment]
Anh đang nói đến "1.000" trong câu này?

> Nếu bạn có 1.000 mẫu trong tập phát triển, và nếu bộ phân loại của bạn có 98,0% độ chính xác, sẽ dễ hơn khi kiểm tra 20 mẫu đã bị phân loại nhầm hơn là cả 980 mẫu được phân loại chính xác

**Comment by tiepvupsu** [comment]
Hôm trước anh thấy lỗi khá nhiều, chắc sửa rồi nhưng chưa cập nhật all_chapters. Anh sẽ cập nhật.

Hiện tại vẫn còn [dòng này](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blame/master/chapters/ch16.md#L47) bị lỗi.

**Comment by rootonchair** [comment]
Anh merge xong update lại all chapter nhé

**Comment by tiepvupsu** [comment]
Okie. Nhân tiện, nếu ở pull request em viết close#426 thì sau khi PR đó được merge, issue này sẽ tự động được đóng.

**Comment by rootonchair** [comment]
oh 😮 . Thank anh.
