### ISSUE TITLE
Acknowledgement

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#427]
Các bạn đã tham gia dịch và review từ đầu cho mình xin tên đầy đủ để Viết lời cảm ơn nhé. Các bạn cứ comment ở dưới.

Mình nêu một số tên mà mình biết:

* Nguyễn Cảnh Thướng
* Lê Khắc Hồng Phúc
* Đoàn Duy Thanh (Thành)
* Phạm Hồng Vinh
* Vũ Đình Quyền
* Vũ Xuân Sơn
* @naml3i 
* @nmdang 
* @seanphan 
* @honghanhh 
* @quangnhat185 
* các bạn còn lại trong danh sách [contributors](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/graphs/contributors?fbclid=IwAR0RIQFfSCRztg6N98BMMmZ10tMMYglQNXifT2694u4aLsyEAbexKGRDqxA)
* các bạn góp công review
* và nhiều bạn khác.

**Comment by honghanhh** [comment]
tên đầy đủ của e là Trần Thị Hồng Hạnh ạ. e cảm ơn a.

**Comment by quangnhat185** [comment]
Tên đầy đủ của em là Nguyễn Lê Quang Nhật ạ.

**Comment by tiepvupsu** [comment]
Cảm ơn hai em. Anh đóng PR này vì nó đang được thực hiện ở #428
