### ISSUE TITLE
Góp ý về việc highlight từ khóa 

### ISSUE THREAD

**Issue by ngcthuong** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#430]
Mình có ghóp ý là nên "đánh dấu" từ khóa trong đoạn văn. Ví dụ như in nghiêng hoặc gạch chân để dễ phân biệt với các từ còn lại. 

Tuy nhiên cần chọn phương thức đánh dấu tránh với các đánh dấu ban đầu của tác giả. 

Mình thấy từ in nghiêng có vẻ ổn, vì tác giả hay dùng in đâm. 

Mọi người thấy sao nhỉ?

**Comment by tiepvupsu** [comment]
Theo mình thì không cần thiết. Nếu muốn nhấn mạnh từ khóa đó thì có thể mở ngoặc và viết từ gốc tiếng Anh ở dạng in nghiêng. Ví dụ.

```
học máy (_machine learning_)
```
