### ISSUE TITLE
Báo lỗi dịch Phần 03 - Chương 21

### ISSUE THREAD

**Issue by kevinvn1709** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#432]
Hi team,
Trong phần dịch về training error và dev error có phần bị sai về % (15% thay vì 5% như bản dịch). Bạn có thể xem hình bên dưới

![image](https://user-images.githubusercontent.com/1281425/70406093-23f3de00-1a72-11ea-88cf-d1606759d761.png)

**Comment by rootonchair** [comment]
Chào @kevinvn1709 ,

Bọn mình đã sửa lại lỗi này trong đợt review lần 2 và sẽ cập nhật lại trên bản all_chapter.

Cảm ơn bạn vì đã bỏ thời gian báo lỗi cho bọn mình

**Comment by tiepvupsu** [comment]
@kevinvn1709 có một số chỗ bản gốc bị sai nên mọi người chủ động sửa. @rootonchair check kỹ lại trước khi sửa nhé.

Ở đây còn một lỗi nữa là cần có dấu `* ` ở dòng "Tỉ lệ lỗi phát triển".

**Comment by rootonchair** [comment]
@tiepvupsu mấy cái này em sửa hết ở Revise 2 rồi anh. Cái này là bản trước revise ạ
