### ISSUE TITLE
Bổ sung các thuật ngữ vào glossary

### ISSUE THREAD

**Issue by rootonchair** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#437]
Cụ thể là các từ:

| Tiếng Anh| Tiếng Việt |
| --- | --- |
| fit | khớp |
| overfit | quá khớp |
| underfit | dưới khớp |
| transcript | bản ghi thoại |
| transcribe | phiên thoại |

Còn thiếu gì nữa không nhỉ?

**Comment by tiepvupsu** [comment]
Anh thấy ok rồi. Mình có thể bổ sung sau nếu thiếu.
