### ISSUE TITLE
Thiết kế bìa

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#440]
@rootonchair em có làm được cái bìa không và trang lót không? Có thể làm tương tự như [hai trang đầu của bản tiếng Anh](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part1.pdf) hoặc đơn giản trên nền trắng cũng được.

Anh thấy có đoạn text, em có thể đề xuất cách dịch ở đây luôn trước khi làm.

**Comment by ngcthuong** [comment]
Bìa chắc ghi thêm tên nhóm dịch chứ nhỉ?

**Comment by rootonchair** [comment]
Để em thử xem có làm lại cái bìa đc không

**Comment by tiepvupsu** [comment]
@ngcthuong File acknowledgement cậu làm sẽ được thêm vào cuối cùng (hoặc ngay sau bìa), file đó cũng có thông tin nhóm dịch rồi.

@rootonchair Không cần tốn quá nhiều công em ạ. Có một cái bìa nền trắng cũng được rồi.

@quangnhat185 khi nào xong bìa và acknowledgement anh em mình thêm vào bản pdf cho đầy đủ nhé.

**Comment by ngcthuong** [comment]
Ý mình là cần có cái tên nhóm dịch ở trang trước. 
Còn trang sau tớ sẽ bố trí sao có đủ hết các mẹt anh em. 
Nên chọn màu nó hấp dẫn tí. Kiếm mấy cái tông màu của mấy con điện thoại ấy

**Comment by thanhcsf** [comment]
Ồ, em cũng tham gia draft ké cái bìa.

**Comment by tiepvupsu** [comment]
@rootonchair chủ động nói chuyện với @duythanhvn trên slack về vụ này nhé.

**Comment by rootonchair** [comment]
Ủa, tên nhóm dịch mình để tên gì vậy các anh?

**Comment by thanhcsf** [comment]
> Ủa, tên nhóm dịch mình để tên gì vậy các anh?

Tiệp Vũ cùng những người bạn 😄

**Comment by ngcthuong** [comment]
Nhóm "Người máy" nha ... viết tắt của "hội những người dịch sách học máy"

**Comment by tiepvupsu** [comment]
> Tiệp Vũ cùng những người bạn 😄

Công sức của cả nhóm, mình không thích ai nổi trội hơn :)

**Comment by tiepvupsu** [comment]
> Ủa, tên nhóm dịch mình để tên gì vậy các anh?

"Nhóm dịch AIviVN" ok không?

**Comment by ngcthuong** [comment]
Mình có comment về cái này một chút là, tuy host trên AIviVN nhưng trên trang chủ thì lại hoàn toàn không có thông tin. Team AIviVN, trừ cậu ra thì cũng ko có ai joint cả. Như vậy lại bị nhầm về contribution. 

Nên mình nghĩ có thể thêm thông tin lên trang chủ, hoặc đặt thêm tên khác, với chú thích ở dưới về AIviVN

**Comment by tiepvupsu** [comment]
Okay, tùy mọi người chọn tên. Mình không có đề xuất nào ngoài việc không đề cập tên riêng một người nào.

**Comment by rootonchair** [comment]
Em nghĩ bỏ vào "dịch bởi Cộng đồng Github" cũng được

**Comment by rootonchair** [comment]
Em quên mất. Còn câu dưới tên cuốn sách em với anh @duythanhvn  dịch là:

| |  
| :---: | 
| "Technical Strategy for AI Engineers, In the Era of Deep Learning" | 
| "Chiến lược kỹ thuật cho các kỹ sư AI trong kỷ nguyên Học Sâu" |

**Comment by tiepvupsu** [comment]
@rootonchair anh thấy ok.

Minor, có quy chuẩn gì về việc viết hoa chữ cái đầu không nhir?

**Comment by tiepvupsu** [comment]
Như @ngcthuong nói trong slack, mình có thể bỏ dấu phẩy sau "AI".

**Comment by rootonchair** [comment]
@tiepvupsu em đã check lại, "Deep Learning" là danh từ riêng nên phải viết hoa các chữ cái đầu

**Comment by tiepvupsu** [comment]
Ý anh là trong bản tiếng Anh các chữ khác như "Engineers", "Era", "In", "Technical" cũng viết hoa, tại sao tiếng Việt là không.

**Comment by ngcthuong** [comment]
Để thử hai bản Viết Hoa Từng Chữ Cái Đầu, và bản viết hoa Từ Khóa xem thử là biết ngay. 

Thấy cái nào đẹp hơn thì viết cũng được, cái này không quan trọng lắm.

**Comment by rootonchair** [comment]
Đó là do chúng là danh từ riêng bên tiếng Anh đó anh. Tuy nhiên nếu mình viết hoa như họ thì lại không phù hợp, nên em đề xuất dòng này để ALL_CAP để đỡ tốn thời gian xử lý.
