### ISSUE TITLE
Đặt tên của nhóm dịch

### ISSUE THREAD

**Issue by ngcthuong** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#442]
Mình nghĩ mỗi nhóm dịch đều nên có tên riêng như một dạng slogan của nhóm. 

Các bạn tham gia đóng góp tên của nhóm nhé, mình có thể dùng tên nhóm này cho cả các project dịch sách sau nữa. 

Tham khảo thêm một số thảo luận trước đó tại #440

**Comment by tiepvupsu** [comment]
Thực ra trong quá trình làm việc, tại mỗi thời điểm chỉ có một tập con số người có thể tham gia được. Các dự án khác nhau sẽ có những người đóng góp khác nhau. Có lẽ nên chọn một tên chung chung.

Mình có đề xuất là "Nhóm dịch Machine Learning cơ bản". Mọi động lực và cách thức hoạt động đều được bắt đầu trên Forum Machine Learning cơ bản. Mình coi đây là một group của cả cộng đồng chứ không của cá nhân nào cả.

**Comment by ngcthuong** [comment]
Tên đó có vẻ được đấy. Cơ mà qua dịch DL mà vẫn tên ML cơ bản thì hơi sao sao :)))

**Comment by tiepvupsu** [comment]
DL là phần nhỏ của ML mà. Nhóm mình dịch ML chung, chẳng may có cuốn DL thôi.

**Comment by ngcthuong** [comment]
Chắc phải thêm nhiều lần chẳng may nữa đấy. :)
Mà tớ băn khoăn cái từ "cơ bản" kia thôi. Vì hiện tại DL vẫn còn 'hiện đại" lắm. 

Nhưng dăm ba năm sau chắc thành "cơ bản" cả thôi 'D

**Comment by thanhcsf** [comment]
Hiện tại em cũng không có đề xuất tên nào. Tuy nhiên, em nghĩ trước mắt thì dự án này bước ra từ Diễn đàn và được sự hỗ trợ từ các thành viên của Diễn đàn; vậy mình cứ sử dụng cái tên này trước cho phù hợp hoàn cảnh. Trong thời gian tới với những dự án khác (từ D2L), nếu cả nhóm có ý tưởng hoặc mong muốn nào trong việc dịch thuật dài hạn hơn thì mình sẽ thảo luận nhiều hơn sau. 

Vì không nhất thiết phải cố gắng lấy một tên cho cả những dự án tương lai mình đang chưa có ý định phải không ạ. 😄

Bình thường em thấy mình hay dùng "Nhóm dịch thuật" thay vì là "Nhóm dịch" không. Vậy em xin phép tạm chốt là "Nhóm dịch thuật Machine Learning cơ bản" để tiến hành sửa bìa được không ạ. 😄
