### ISSUE TITLE
Canh giữa hình ảnh, một số hình ảnh hiển thị sai kích thước

### ISSUE THREAD

**Issue by rootonchair** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#449]
* Trong phiên bản hiện tại, các hình ảnh đều không được canh giữa nên có thể gây ra khó chịu khi đọc.

* Một số hình hiển thị sai kích thước, ví dụ như các phương trình ở chương 44, 45 và các hình ở chương 53, 54

**Comment by quangnhat185** [comment]
Một điều nữa là mình recommend dùng cú pháp html dưới đây để căn giữa nhằm hạn chế lỗi khi convert sang pdf file:

```
<p align="center">
  <img src="image_path">
</p>
```

Trường hợp muốn resize ảnh thì có thể thêm "width" để define bề rộng với đơn vị pixel vào sau link ảnh như dưới đây:

```
<p align="center">
  <img src="image_path" width="600">
</p>
```

**Comment by tiepvupsu** [comment]
@rootonchair em chỉnh theo cách của @quangnhat185 được không? Hai em chủ động thảo luận rồi update nhé.

**Comment by tiepvupsu** [comment]
Có cập nhật gì không @quangnhat185 @rootonchair?

**Comment by rootonchair** [comment]
@tiepvupsu em đang test vài thứ để tự động hóa việc chèn html.

**Comment by quangnhat185** [comment]
@rootonchair Trong file [pdf_converter.py](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/pdf_converter.py) mình có code chèn html đó bạn có thể tham khảo, nếu có khó khăn gì bạn có thể đưa lên đây đề mọi người cùng trao đổi

**Comment by rootonchair** [comment]
@quangnhat185 cảm ơn bạn nhiều. Để mình check.
