### ISSUE TITLE
Dịch những ảnh có công thức toán học

### ISSUE THREAD

**Issue by rootonchair** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#459]
`C44_01`
![C44_01](https://user-images.githubusercontent.com/23548268/71321999-8f1ec500-24f4-11ea-9990-162eb490789c.png)
`C45_01`
![C45_01](https://user-images.githubusercontent.com/23548268/71322000-90e88880-24f4-11ea-8b45-0664d22a379b.png)
`C39_01`
![C39_01](https://user-images.githubusercontent.com/23548268/71322002-980f9680-24f4-11ea-9da3-6836baa3f12b.png)
`C39_02`
![C39_02](https://user-images.githubusercontent.com/23548268/71322004-9a71f080-24f4-11ea-9443-c60e783932e9.png)

Trong cuốn sách có những ảnh chứa công thức như trên. Em dự định 2 tấm C44 và C45 chỉ dịch "Output" và "Score" thôi. Còn 2 tấm của C39 thì là "InternetImg" và "MobileImg". Mọi người thấy dịch Anh-Việt lộn xộn như vậy có ổn không?

**Comment by tiepvupsu** [comment]
Anh nghĩ dễ nhất là mình dịch hết, ở đây cũng chỉ có một vài từ. Để đơn giản thì em làm các ảnh trên Latex ấy, đừng sửa trực tiếp trên ảnh.

MobileImg dịch là `Ảnh_Điện_Thoại`, InternetImg là `Ảnh_Internet`.

**Comment by tiepvupsu** [comment]
C39_01
![](https://i.ibb.co/5Fp7XJd/C39-01.png)

C39_02
![](https://i.ibb.co/1syJFQG/C39-02.png)

C44_01
![](https://i.ibb.co/87DmqL3/C44-01.png)

C45_01 
![](https://i.ibb.co/89zyVxh/C45-01.png)

Em muốn sửa thì vào đây:
https://www.overleaf.com/project/5dffa1a77979160001d1344a

**Comment by rootonchair** [comment]
@tiepvupsu những tấm anh làm em thấy ổn cả. Tuy nhiên hai tấm đầu anh sửa lại là `\underset{\theta}{min}` giùm em nhé. Không hiểu sao em không có quyền truy cập vô link của anh

**Comment by tiepvupsu** [comment]
Em xem ở đây rồi sửa luôn nhé @rootonchair https://www.overleaf.com/9299826158kcpdbtyxfrjh

**Comment by tiepvupsu** [comment]
Đây nhá.
![image](https://user-images.githubusercontent.com/2201237/71419578-f9368780-2624-11ea-81f7-3cfa8c3a6fc0.png)

![image](https://user-images.githubusercontent.com/2201237/71419583-03f11c80-2625-11ea-8e73-8b9c09981a77.png)

**Comment by rootonchair** [comment]
![C39_01](https://user-images.githubusercontent.com/23548268/71419831-40b02880-26a4-11ea-8475-1b9b357411cc.png)
![C39_02](https://user-images.githubusercontent.com/23548268/71419833-4443af80-26a4-11ea-8453-01ba0c02bd45.png)
Em đã sửa lại cho đúng bản gốc. Thank anh Tiệp nhiều
