### ISSUE TITLE
Chọn font chữ, căn lề, add ảnh cover... cho pdf file

### ISSUE THREAD

**Issue by quangnhat185** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#462]
Mình viết code thực hiện một số thay đổi cho pdf file như sau:

- Thêm ảnh cover vào đầu trang
- Tăng font-size
- Căn lề top/left/right/bottom: 2.5cm
- Align text thành justify
- Tạo thêm 1 file pdf sử dụng font **Times New Roman**. Mọi người vote để lựa chọn font **Markdown** (file Origin) hay font **Times New Roman** cho bản pdf ở dưới nhé. 

Font Markdown: :+1: 
Font Times New Roman: :heart: 

[(Origin)all_chapters.pdf](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/files/3998430/Origin.all_chapters.pdf)
[(Timenewsroman)all_chapters.pdf](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/files/3998431/Timenewsroman.all_chapters.pdf)

[(Origin)all_chapters_vietnamese_only.pdf](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/files/3998620/Origin.all_chapters_vietnamese_only.pdf)
[(Timenewsroman)all_chapters_vietnamese_only.pdf](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/files/3998621/Timenewsroman.all_chapters_vietnamese_only.pdf)

**Comment by thanhcsf** [comment]
Ảnh bìa vầy là "toang" rồi ông giáo ạ 😞

**Comment by quangnhat185** [comment]
> Ảnh bìa vầy là "toang" rồi ông giáo ạ

Tôi cũng khổ lắm bác giáo ạ. Khi căn lề nó bắt căn tất cả các trang, ,mình ko customize được.  Giờ có một cách là tạo một file pdf bìa trước rồi merge với nội dung sau :cry:

**Comment by thanhcsf** [comment]
Tôi hỏi bác trước rồi, thấy bác chốt được tôi nào có biết 😢 thế giờ bác xử lý nội dung ra file pdf đi, tôi merge hộ bác thêm cái bìa là mình xem như xong.

**Comment by quangnhat185** [comment]
Trước thì không có vấn đề gì, sau thêm vụ căn lề nên nó mới toang thế này :smile:. Ông up lại giúp tôi file pdf của bìa rồi tôi thêm code tự merge luôn

**Comment by rootonchair** [comment]
Anh up thêm bản chỉ tiếng Việt được không anh?

**Comment by quangnhat185** [comment]
> Anh up thêm bản chỉ tiếng Việt được không anh?

@rootonchair Anh đã up bổ sung rồi nhé

**Comment by rootonchair** [comment]
Sao mấy cái heading của mình nhỏ quá nhỉ? Có ai thấy vậy không?

**Comment by tiepvupsu** [comment]
> Sao mấy cái heading của mình nhỏ quá nhỉ? Có ai thấy vậy không?

Anh cũng thấy thế, khả năng là do mình set fontsize rồi nó áp dụng cho toàn bộ luôn.

Ca này hơi loằng ngoằng nhỉ. Không chỉnh font thì chữ nhỏ quá, chỉnh thì lại chỉnh hết toàn bộ.

**Comment by tiepvupsu** [comment]
Về phần font chữ, mình thấy để nguyên markdown đẹp hơn. Times New Romans nhìn càng ngày càng xấu.

Mình thì vẫn thấy [font của latex](https://github.com/tiepvupsu/tiepvupsu.github.io/blob/master/Math_ML.pdf) là đẹp nhất. Nhưng chắc convert kiểu này không lấy được font đó.

**Comment by quangnhat185** [comment]
> > Sao mấy cái heading của mình nhỏ quá nhỉ? Có ai thấy vậy không?
> 
> Anh cũng thấy thế, khả năng là do mình set fontsize rồi nó áp dụng cho toàn bộ luôn.
> 
> Ca này hơi loằng ngoằng nhỉ. Không chỉnh font thì chữ nhỏ quá, chỉnh thì lại chỉnh hết toàn bộ.

Chỉnh lại cũng không phức tạp lắp đâu anh, chỉ cần thêm một dòng html chỉnh size cho header nữa là xong. Thực ra là em chỉ mới tăng cỡ chữ nội dung chứ chưa tăng cỡ chữ header nên hơi mất cân đối

> Về phần font chữ, mình thấy để nguyên markdown đẹp hơn. Times New Romans nhìn càng ngày càng xấu.
> 
> Mình thì vẫn thấy [font của latex](https://github.com/tiepvupsu/tiepvupsu.github.io/blob/master/Math_ML.pdf) là đẹp nhất. Nhưng chắc convert kiểu này không lấy được font đó.

Nếu font chữ latex anh dùng được hỡ trợ bởi html ([check ở đây](https://en.wikipedia.org/wiki/Font_family_(HTML))) thì vẫn convert được.  Vấn đề là em không biết tên font latex của anh là gì :confused:

**Comment by thanhcsf** [comment]
@quangnhat185 nó tên là Latex đó Nhật 😄 https://en.wikibooks.org/wiki/LaTeX/Installation
Điều chỉnh thêm cả phần các phần phân cách các chương nữa Nhật nha. Nó thiệt là bự và nằm chính giữa trang giấy là đẹp.

**Comment by rootonchair** [comment]
Nó cũng có tên khác là Computer Modern. Em có tìm thử cách cho font này vào html. Anh thử xem

https://stackoverflow.com/questions/6476351/how-to-use-the-computer-modern-font-in-webpages

**Comment by quangnhat185** [comment]
> @quangnhat185 nó tên là Latex đó Nhật  https://en.wikibooks.org/wiki/LaTeX/Installation
> Điều chỉnh thêm cả phần các phần phân cách các chương nữa Nhật nha. Nó thiệt là bự và nằm chính giữa trang giấy là đẹp.

Trong Latex cũng phải chọn Font mà nhỉ? **https://en.wikibooks.org/wiki/LaTeX/Fonts**

**Comment by rootonchair** [comment]
> Điều chỉnh thêm cả phần các phần phân cách các chương nữa Nhật nha. Nó thiệt là bự và nằm chính giữa trang giấy là đẹp.

Cái này nếu làm được là chuẩn như bản gốc luôn

**Comment by thanhcsf** [comment]
@quangnhat185 nào có 😄
> By default, LaTeX uses **Computer Modern**, a family of typefaces designed by Donald Knuth for use with TeX.

Giới thiệu cũng tùm lum, quy về một mối. em Vinh cũng đưa thêm một bài hướng dẫn, ông giáo xem thử nào 😄

**Comment by aivivn** [comment]
Mọi người ơi, cái này ngoài font chữ còn gì phải kiểm tra nữa không? Liệu xong hôm nay được không?

@quangnhat185 anh đã merge phần acknowledgment vào rồi, em thêm file này như là một "Phần" mới nhé.

**Comment by rootonchair** [comment]
Em thấy không còn gì để thay đổi thêm nữa. Anh Nhật làm xong là xong luôn.

**Comment by quangnhat185** [comment]
> Mọi người ơi, cái này ngoài font chữ còn gì phải kiểm tra nữa không? Liệu xong hôm nay được không?
> 
> @quangnhat185 anh đã merge phần acknowledgment vào rồi, em thêm file này như là một "Phần" mới nhé.

File pdf thì em nghĩ hôm nay có thể xong. Còn code để automate thì em phải đẩy một PR khác. Cho em hỏi là phần Acknowledgment mình add vào sau trang bìa hay ở cuối sách vậy?

**Comment by ngcthuong** [comment]
Để ở đầu đi em

**Comment by quangnhat185** [comment]
File pdf đã sửa font, add cover mới, thêm acknowledgement đã ra lò vừa thổi vừa ăn đây:

[(Final)all_chapters_vietnamese_only.pdf](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/files/4000443/Final.all_chapters_vietnamese_only.pdf)

[(Final)all_chapters.pdf](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/files/4000444/Final.all_chapters.pdf)

**Comment by ngcthuong** [comment]
kích thước ảnh file ACK hiện tại hơi kỳ kỳ  một chút. Đặc biệt là ACK cho giai đoạn 2.

**Comment by ngcthuong** [comment]
Table ở ACK cũng hơi dị vì khoảng cách nó không đều 

![image](https://user-images.githubusercontent.com/6524339/71445784-102dc480-2760-11ea-83dc-3b9ef5ff9f0d.png)

**Comment by ngcthuong** [comment]
Mình không để ý, cần xóa dòng (Nếu bạn bổ xung ....)

**Comment by ngcthuong** [comment]
Cần đánh số trang nữa.

**Comment by quangnhat185** [comment]
> Cần đánh số trang nữa.

> kích thước ảnh file ACK hiện tại hơi kỳ kỳ một chút. Đặc biệt là ACK cho giai đoạn 2.

Ý là ảnh bị nhỏ hay sao anh?

**Comment by tiepvupsu** [comment]
Để mình sửa lại bảng glossay. Mình quên mất là bảng này cũng cần đưa vào file pdf 
và phải làm bản Việt-Anh nữa :(.

Hôm nay không xong thì mình để tối mai lên cũng không sao. 26/12 là lễ tặng quà :D

**Comment by aivivn** [comment]
> Table ở ACK cũng hơi dị vì khoảng cách nó không đều
> 
> ![image](https://user-images.githubusercontent.com/6524339/71445784-102dc480-2760-11ea-83dc-3b9ef5ff9f0d.png)

fixed
https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/pull/466
