### ISSUE TITLE
Lỗi thụt đầu dòng chương 47

### ISSUE THREAD

**Issue by rootonchair** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#467]
![image](https://user-images.githubusercontent.com/23548268/71462211-2e89d380-27e5-11ea-9174-dd614d65e657.png)

**Comment by tiepvupsu** [comment]
Cái này khá nhỏ, mình có thể fix nhanh bằng cách cho các câu đó vào trong ngoặc kép.
