### ISSUE TITLE
Tạo mới ảnh C51_03 và C51_04

### ISSUE THREAD

**Issue by rootonchair** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#468]
Các ảnh cũ có kích thước nhỏ so với bản gốc và không đẹp. Cần tạo mới. @duythanhvn phần này em nhờ anh được không?
`C51_03`
![C51_03](https://user-images.githubusercontent.com/23548268/71462506-0e0e4900-27e6-11ea-8077-684d661f00cc.png)
`C51_04`
![C51_04](https://user-images.githubusercontent.com/23548268/71462508-0f3f7600-27e6-11ea-9a90-1e793a68cead.png)

![image](https://user-images.githubusercontent.com/23548268/71462561-31d18f00-27e6-11ea-85ff-83b5caa2e8de.png)

Edit:
`C53_01` và `C54_01` cũng là những ảnh này

**Comment by thanhcsf** [comment]
Uhm em.
