### ISSUE TITLE
Lỗi ảnh chương 52

### ISSUE THREAD

**Issue by rootonchair** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#469]
![image](https://user-images.githubusercontent.com/23548268/71462759-f5526300-27e6-11ea-96ec-771d47074404.png)

Lý tưởng nhất là tạo một ảnh mới từ bên bản gốc và dịch trên đó

**Comment by tiepvupsu** [comment]
Mấy cái này minor @rootonchair ơi. Quan trọng nhất là xong bản PDF toàn bộ để nhóm công bố đã. Những cái minor này mình rảnh thì làm thôi.

**Comment by rootonchair** [comment]
@tiepvupsu  Vậy cái này để sau ạ. Em thấy ngoài mấy cái này ra thì phần pdf của mình hoàn thiện rồi.

**Comment by ngcthuong** [comment]
Xem bản pdf mới nhất ở đâu ấy nhỉ

**Comment by rootonchair** [comment]
Hiện thì em mới chỉ upload bản merge trên slack. Còn phải đợi anh Nhật push code chuyển pdf mới lên thì mới tạo được bản hoản chỉnh.
