### ISSUE TITLE
Check list bản pdf cuối.

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#471]
Mình tạo checklist trước khi công bố bản pdf hoàn chỉnh, mọi người bổ sung nhé.

* [x] Bố cục 
   - Bìa
   - Giới thiệu của nhóm dịch (optional, có thể thêm sau)
   - Mục lục
  - Nội dung chính
   - Glossary (toàn bộ)
   - Ack

* [x] font chữ chính 13
* [x] Bìa không căn lề
* [x] Tạo một file bash sao cho chỉ cần chạy file đó là có file pdf mới mỗi khi nội dung được cập nhật
* [ ] others

**Comment by quangnhat185** [comment]
File Acknowledgment.md mình nên merge vào file all_chapters.md luôn hay là để riêng rồi merge sau khi convert sang pdf anh nhỉ?

**Comment by tiepvupsu** [comment]
@quangnhat185 lý tưởng nhất là tất cả merge vào all_chapers.md. Sao cho bản md đọc online và bản pdf offline càng giống nhau càng tốt.

**Comment by thanhcsf** [comment]
Sắp xếp của anh là Nội dung nằm trước hay sau Glossary vậy anh nhỉ?

**Comment by tiepvupsu** [comment]
@quangnhat185 úi quên cái quan trọng nhất. Anh để nó vào trước Ack rồi.

**Comment by tiepvupsu** [comment]
Mọi thứ trong checklist đã hoàn thiện, chỉ có cái là mình không thêm glossary vào mà chỉ để selected như danh sách rút gọn của @ngcthuong.

Mọi người về trang của của repo xem cập nhật. Mình nghĩ cần revise lại acknowlegement là xong.
