### ISSUE TITLE
Merge file acknowledgement.md vào all_chapters.md và all_chapters_vietnamese_only.md

### ISSUE THREAD

**Issue by quangnhat185** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#477]
Sau khi thảo luận thì mọi người đã nhất trí thì thay vì tạo file pdf riêng của acknowledgement rồi merge, chúng ta sẽ merge trực tiếp vào file 2 file chung là all_chapters và all_chapters_vietnamese_only. 

#471

**Comment by rootonchair** [comment]
Vậy anh nhớ update lại 2 file `create_pdf.sh` và `create_pdf.bat`

**Comment by tiepvupsu** [comment]
Done ở #485 và #486
