### ISSUE TITLE
Comment nhỏ về chỉnh dòng ở bản pdf

### ISSUE THREAD

**Issue by ngcthuong** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#493]
Mình có một số comment nhỏ mình viết lại ở đây chủ yếu là xuống dòng sao cho nó nhìn hợp lý hơn 

Hiện tại cần thêm một số xuống dòng để các trang nhảy đoạn cho đẹp, không nên viết dạng đoạn văn bị tách làm hai do khác trang. 

Điển hình như ví dụ dưới đây. Chỉ cần xuống dòng 1 cái nữa là đẩy đoạn văn dở sang trang kia sẽ trông gọn hơn rất nhiều. 

![image](https://user-images.githubusercontent.com/6524339/71539439-83615180-297f-11ea-991c-d55a50f1d578.png)

![image](https://user-images.githubusercontent.com/6524339/71539441-8bb98c80-297f-11ea-831f-3f4c76eadbc6.png)

Phần chú thích mình nghĩ nên đặt ở cuối trang hoặc cách thêm hẳn một dòng nữa cho nó khác biệt. Không nên viết dính như thé này. 

![image](https://user-images.githubusercontent.com/6524339/71539448-b1df2c80-297f-11ea-930e-72440ded02b1.png)

![image](https://user-images.githubusercontent.com/6524339/71539648-c7098a80-2982-11ea-9d41-47e7902bb85e.png)

**Comment by ngcthuong** [comment]
Chỉnh lại bảng biểu --> cân giữa, sửa kích thước bảng. Trang 17. 

![image](https://user-images.githubusercontent.com/6524339/71539477-d2a78200-297f-11ea-8fe6-a307d8a9bdd2.png)

![image](https://user-images.githubusercontent.com/6524339/71539479-d804cc80-297f-11ea-9630-08fa5836640e.png)


![image](https://user-images.githubusercontent.com/6524339/71539617-3af76300-2982-11ea-97d8-3529e3966104.png)

**Comment by ngcthuong** [comment]
Bảng này chữ cũng bị lệch, mình có nên căn giữa? 
![image](https://user-images.githubusercontent.com/6524339/71539494-fe2a6c80-297f-11ea-9638-0389dc37db57.png)

**Comment by ngcthuong** [comment]
Sửa từ code --> mã nguồn cho giống với hình 
Thí nghiệm ---> thử nghiêm?

![image](https://user-images.githubusercontent.com/6524339/71539538-dd164b80-2980-11ea-8454-cbe6ec7b71fb.png)

**Comment by ngcthuong** [comment]
nên thêm dòng giữa hai item lớn để tăng độ rõ ràng của các phàn
Ví dụ thêm một dòng trước khi bắt đầu mục 3. 

![image](https://user-images.githubusercontent.com/6524339/71539570-91b06d00-2981-11ea-9973-e692509e724b.png)

**Comment by ngcthuong** [comment]
Dưới mỗi bảng, hình vẽ nên có thêm phần cách xuống dòng để nhìn cho rõ.
Ở các bảng dưới, trong phần ghi chú đã là "Tổng %" rồi thì bên trong không cần ghi "%"

![image](https://user-images.githubusercontent.com/6524339/71539592-cde3cd80-2981-11ea-90a7-57d0e63f3438.png)

![image](https://user-images.githubusercontent.com/6524339/71539603-efdd5000-2981-11ea-9d50-1168ab1e722e.png)

**Comment by ngcthuong** [comment]
Chương 17 có thể để hình kích thước to hơn để dàn 2 trang đẹp hơn 

![image](https://user-images.githubusercontent.com/6524339/71539606-071c3d80-2982-11ea-9f6c-8ca2693f74b9.png)

**Comment by ngcthuong** [comment]
Chương 18 với 17 là hình giống nhau y chang? Có gì sai sót ở đây ko nhỉ

![image](https://user-images.githubusercontent.com/6524339/71539612-20bd8500-2982-11ea-8c33-040e4b2d6b34.png)

**Comment by ngcthuong** [comment]
Sửa tiêu đề chương 20 cho nó gọn, hiện tại là 2 dòng trông rất là cụt
 
--> Độ chệc và phương sai: hai nguồn lỗi lớn
![image](https://user-images.githubusercontent.com/6524339/71539620-4c406f80-2982-11ea-8076-1566af498502.png)

**Comment by ngcthuong** [comment]
Sửa tiêu đè ---> Bỏ từ *Những*. 
![image](https://user-images.githubusercontent.com/6524339/71539628-72fea600-2982-11ea-9a08-f4d8dd4cb683.png)

**Comment by ngcthuong** [comment]
Điều chỉnh lại các khoảng cách để không bị trồi ra một ít ở trang này

![image](https://user-images.githubusercontent.com/6524339/71539634-9590bf00-2982-11ea-8388-9e36557acda7.png)

**Comment by ngcthuong** [comment]
Chương 30 và 31 dịch đang hơi khác nhau 

![image](https://user-images.githubusercontent.com/6524339/71539642-b22cf700-2982-11ea-84e8-6c2b72fd71de.png)
![image](https://user-images.githubusercontent.com/6524339/71539643-b527e780-2982-11ea-9985-b92a82f78750.png)

**Comment by ngcthuong** [comment]
Ảnh công thức size quá to 
![image](https://user-images.githubusercontent.com/6524339/71539655-e6081c80-2982-11ea-945e-93707086446d.png)

![image](https://user-images.githubusercontent.com/6524339/71539661-ee605780-2982-11ea-99fa-63934dca284f.png)

**Comment by ngcthuong** [comment]
Bảng thuật ngữ càn chỉnh lại kích thước
![image](https://user-images.githubusercontent.com/6524339/71539672-2798c780-2983-11ea-969e-7dcfba43882a.png)

**Comment by ngcthuong** [comment]
Thêm các dấu xuống dòng cho ACK 

![image](https://user-images.githubusercontent.com/6524339/71539675-3aab9780-2983-11ea-9727-b1fe99cf4630.png)

![image](https://user-images.githubusercontent.com/6524339/71539680-4303d280-2983-11ea-9169-4c0033f6eb54.png)

**Comment by aivivn** [comment]
Các dấu xuống dòng không chỉnh được vì nó theo markdown. Trong markdown cậu có xuống bao nhiêu dòng thì nó vẫn như thế.

Các hình tớ đã chỉnh đáng kể trong bản mới nhất. Cậu check lại xem.
