### ISSUE TITLE
Lỗi chính tả mục 38.

### ISSUE THREAD

**Issue by phamquocbao0311** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#499]
Phía trên phần chú thích có câu:  
*Điều này có nghĩa là có rất ít nhược điểm (ngoài chi phí tính toán) khi bao gồm tất cả các dữ liệu nhưng lại có thể có những ưu điểm **lơn**. Ngược lại, dữ liệu của Thành phố New York với Detroit và Michigan không nhất quán. Cho cùng một x (kích thước của ngôi nhà), giá nhà rất khác nhau tùy thuộc vào vị trí ngôi nhà.*  
Từ in đậm sai chính tả nên sửa lại **"lơn"** thành **"lớn"**.

**Comment by duythanhvn** [comment]
Chào bạn,

Cảm ơn bạn đã phản hồi. Bạn có thể cho mình xin đường dẫn đến phần thông tin này được không nhỉ?

**Comment by phamquocbao0311** [comment]
Chào bạn,
Đây là link có lỗi sai chính tả:
https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/chapters/book_vn.md#ch38
Sincerely!

Vào Th 2, 30 thg 12, 2019 vào lúc 16:18 Thanh Doan, Steve <
notifications@github.com> đã viết:

**Comment by tiepvupsu** [comment]
Cảm ơn bạn. Mình sẽ sửa lỗi này.
