### ISSUE TITLE
Tạo thư mục ảnh

### ISSUE THREAD

**Issue by aivivn** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#5]
* [x] Tạo một thư mục ảnh `imgs` cho toàn bộ các chapter.
* [x] Viết hướng dẫn đặt tên ảnh trong file `imgs/README.md`.
* [x] Link tới file hướng dẫn này trong file `README.md`.

**Comment by ngcthuong** [comment]
Done

**Comment by aivivn** [comment]
Khi nào merge xong #8 thì mới được close issue này.
