### ISSUE TITLE
Chương 10 dịch chu kì phát triển từ 3. thí nghiệm --> 3. kinh nghiệm

### ISSUE THREAD

**Issue by phamdinhkhanh** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#500]
![image](https://user-images.githubusercontent.com/24260166/71651466-4bc42200-2d50-11ea-852d-b244b6323f44.png)

[Chương 10](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/chapters/ch10.md) tác giả đang trình bày quy trình để phát triển dự án từ 1. ý tưởng -->3. thí nghiệm. Hình vẽ dịch sai bước 3 từ `thí nghiệm` sang `kinh nghiệm`.

**Comment by tiepvupsu** [comment]
Cảm ơn @patrickphatnguyen 

@rootonchair Em xem số có bị sai luôn không nhé. Hình như đang là 1, 3, 3 thay vì 1, 2, 3.

**Comment by rootonchair** [comment]
@tiepvupsu anh feedback đúng. "Mã nguồn" cũng không trùng khớp với phần dịch phía trên. Để em sửa lại luôn.

![image](https://user-images.githubusercontent.com/23548268/71652000-a0699c00-2d54-11ea-821a-d518b5cf5fcd.png)

Cảm ơn đóng góp của @phamdinhkhanh

**Comment by tiepvupsu** [comment]
@rootonchair em đổi `code` thành `mã nguồn` nhé. Em có build lại luôn được pdf không?

**Comment by rootonchair** [comment]
@tiepvupsu có, em build được nha anh

**Comment by phamdinhkhanh** [comment]
> @rootonchair em đổi `code` thành `mã nguồn` nhé. Em có build lại luôn được pdf không?

em nghĩ trong sơ đồ thì bước 3 từ `Kinh nghiệm` phải là `Thí nghiệm` hoặc `Thực nghiệm`. Để từ `Kinh nghiệm` là sai mất ý của tác giả giải thích ở ngay trên: `3. tiến hành một thí nghiệm để đo mức hiệu quả của ý tưởng.`

**Comment by rootonchair** [comment]
Mình đã nhắm rõ vấn đề. Mình sẽ sửa theo đề xuất của bạn lẫn một lỗi mà mình mới phát hiện ra.
