### ISSUE TITLE
Chỉnh sửa bản dịch chương 6

### ISSUE THREAD

**Issue by ngcthuong** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#62]

**Comment by quangnhat185** [comment]
Em sẽ dịch chương này ạ

**Comment by quangnhat185** [comment]
#91

**Comment by tiepvupsu** [comment]
Bản dịch đầu tiên của chương này đã được merge ở #91. Tuy nhiên, vẫn cần một PR nữa để giúp hoàn thiện về mặt ngôn ngữ.
Cảm ơn @quangnhat185

**Comment by ngcthuong** [comment]
Để mình chỉnh bản này.

**Comment by tiepvupsu** [comment]
Bản này đã được chỉnh chưa nhỉ @ngcthuong?

**Comment by ngcthuong** [comment]
Mình đang đi hội nghị nên hơi bận xí. Cuối tuần này mình sẽ update

**Comment by tiepvupsu** [comment]
> Mình đang đi hội nghị nên hơi bận xí. Cuối tuần này mình sẽ update

@ngcthuong ping ^

**Comment by ngcthuong** [comment]
mình vừa tạo pull request ở #262
