### ISSUE TITLE
Update bản dịch tiếng Việt chương 3

### ISSUE THREAD

**Issue by quangnhat185** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#66]
Em update bản dịch tiếng việt cho chapter 03. Có gì chưa ổn các anh góp ý để các chương tới em có thể dịch tốt hơn. 

Em cũng update 2 term mới trong glossarry là deep learning -> deep learning và supervised learning -> học có giám sát.

**Comment by aivivn** [comment]
Cảm ơn em. Anh đóng issue này vì nó trùng với #15.
