### ISSUE TITLE
Lưu ý khi dịch các chương sau 14

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#76]
Vì các chương cần được dịch nhất quán, thứ tự review để merge vào master sẽ theo thứ tự trong sách. Việc này đồng nghĩa với việc tại thời điểm review chương bạn dịch, có thể có nhiều từ thuật ngữ đã được quyết định dịch theo hướng khác. Khi đó bạn phải thay đổi cách dịch cho phù hợp.

Thay vì dịch các chương về sau, Ban điều hành sẽ tập trung review hoàn thiện các chương ban đầu trước. Bạn cũng có thể đóng góp bằng cách tham gia review các chương đã được dịch.

**Comment by naml3i** [comment]
Rất đồng ý! 
Chưa cần đến chương 14 mà mới chỉ 5, 6 chương đầu mình đã thấy tiềm năng phát sinh nhiều vấn đề  dịch thuật do bảng glossary còn quá ít so với thực tế gặp khi dịch. 
Nên có các milestone để thống nhất thuật ngữ theo từng chặng và để quality control tổng thể các chương đã dịch (không chỉ ở thuật ngữ) (ở đây đã chọn mốc là chương 14).

**Comment by tiepvupsu** [comment]
Mình chọn chương 14 vì nó là kết thúc phần đầu tiên của cuốn sách. Có lẽ phải ưu tiên cập nhật glossary của các chương trước. Nếu có bạn nào lọc các glossary tiếng Anh để đưa vào *cột thứ nhất) của bảng Thuật ngữ Anh Việt ở file glossary thì sẽ rất tốt.

**Comment by quangnhat185** [comment]
Em đồng ý. Nên làm thật kỹ các chương đầu thứ nhất là để thống nhất được template chuẩn và thứ hai nữa là để contributors như bọn em quen với workflow của project mình ạ.
