### ISSUE TITLE
Thống nhất glossary cho các chương từ 1 đến 14.

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#78]
Mình nghĩ trước hết cần đưa hết các thuật ngữ tiếng Anh của [Phần 1](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part1.pdf) vào trong file [`glossary.md`](https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/blob/master/glossary.md). Sau đó dịch tiếng Việt trong bảng này cho hoàn thành trước khi tiến hành dịch các chương từ 2 đến 14.

Rất mong có bạn nhận làm việc này.

**Comment by ngcthuong** [comment]
Để mình làm cho

**Comment by tiepvupsu** [comment]
Uh, vậy ưu tiên làm cái glossary với *chỉ tiếng Anh* trước để tớ approve đã. Những từ dễ dịch có thể thêm luôn, còn những từ khó dịch để tạo từng pull request riêng.

**Comment by lkhphuc** [comment]
Tiến độ task này tới đâu rồi nhỉ, tại mình không thấy open pull request nao? Không biết là đã xong hết chưa để bắt đầu dựa trên nó để dich/review các chapter khác.

**Comment by lkhphuc** [comment]
Mình có nên thêm 1 cột nữa, để dẫn link tới vị trí của thuật ngữ trong context, và link tới các issues, pull requests thảo luận về thuật ngữ đó không?

Ví dụ giờ mình muốn thảo luận về từ "mạng neural" nhưng không chắc là đã được thảo luận và đưa ra quyết định cuối cùng chưa, sợ tạo issue nhiều lại thành ra spam.

Edit: PR #87

**Comment by tiepvupsu** [comment]
Mình đồng ý. 

@ngcthuong có tạo cái https://github.com/aivivn/Machine-Learning-Yearning-Vietnamese-Translation/pull/81 và đã được merge.

Những từ khó mình nghĩ cứ tạo Issue rồi bàn luận. Nhưng để vấn đề từ khó không block tiến độ dịch thì có thể dùng trước một cách dịch, sau đó sửa lại ở toàn bộ các chương nếu cần. Cuốn này mỏng, việc search rồi sửa lại không có gì phức tạp.

**Comment by tiepvupsu** [comment]
Hiện toàn bộ glossary của phần này đều đã có.
