### ISSUE TITLE
Bổ sung thuật ngữ tiếng Anh từng phần vào glossary

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/Machine-Learning-Yearning-Vietnamese-Translation#96]
Bổ sung thuật ngữ tiếng Anh từng phần vào `glossary.md`.

Phần bổ sung này chỉ bao gồm việc đưa các từ tiếng Anh vào cột thứ nhất. Nghĩa tiếng Việt sẽ được thảo luận trong các Pull Request riêng.

Để dễ review, các thuật ngữ theo từng phần cần được thêm bằng các pull request **riêng biệt**.
Dưới đây là bản gốc của các phần 

* [x] [phần 2](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part2.pdf)
* [x] [phần 3](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part3.pdf)
* [x] [phần 4](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part4.pdf)
* [x] [phần 5](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part5.pdf)
* [ ] [phần 6](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part6.pdf)
* [ ] [phần 7](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part7.pdf)
* [ ] [phần 8](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part8.pdf)
* [ ] [phần 9](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part9.pdf)
* [ ] [phần 10](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part10.pdf)
* [ ] [phần 11](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part11.pdf)
* [ ] [phần 12](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part12.pdf)
* [ ] [phần 13](https://github.com/ajaymache/machine-learning-yearning/blob/master/machine-learning-yearning-part13.pdf)

**Comment by thanhcsf** [comment]
Em thấy đã có 1 pull request đang updating glossary cho phần 1, như vậy sẽ có conflict. Em cứ bổ sung rồi resolve sau hay sao anh nhỉ?

**Comment by ngcthuong** [comment]
Phải resolve conflict mới approve được. Có hướng dẫn đó em.

**Comment by tiepvupsu** [comment]
> Em thấy đã có 1 pull request đang updating glossary cho phần 1, như vậy sẽ có conflict. Em cứ bổ sung rồi resolve sau hay sao anh nhỉ?

@duythanhvn 
Anh đã merge PR đó. Em tạo luôn bây giờ sẽ không bị conflict. Chú ý giữ theo thứ tự bảng chữ cái nhé.
Cảm ơn em nhiều.

**Comment by freeloneman** [comment]
Mình nghĩ Glossary nên xếp theo thứ tự của chương mà thuật ngữ đó xuất hiện đầu tiên để dễ tra (người đọc đến chương nào thấy thuật ngữ đó thì tra cứu, khi đã biết rồi mà gặp thuật ngữ đó trong các chương sau thì không cần phải tra nữa). Mỗi chương thì thuật ngữ xếp theo thứ tự a, b, c

**Comment by ngcthuong** [comment]
Mình thì không nghĩ như vậy vì tốn thời gian và không có ý nghĩa gì nhiều. Phần lớn hay gần như tât cả các cuốn sách mình đọc chỉ có 1 glossary. Không xếp theo chương. 

Nên để hiện tại theo mình là đẹp nhất

**Comment by freeloneman** [comment]
Mình xem hướng dẫn thì thấy muốn chỉnh sửa thuật ngữ nào phải dùng PR, như vậy liệu có nhiều PR quá không?
Thuât ngữ đầu tiên mình muốn bàn nằm ở ngay tựa sách: machine learning (ML). Nếu không dịch ra tiếng Việt thì các chữ "learning" nằm xuyên suốt cuốn sách thì sao? Nếu "learning algorithm" dịch là "thuật toán học" thì sao ML không dịch được? ML có sách dịch là "máy học", có sách dịch là "học máy". Về cấu trúc tiếng Anh thì machine learning nghĩa là "việc học của máy", tức việc con người dạy cho máy để hoạt động giống như con người (chứ không phải máy dạy cho con người học), do đó mình nghĩ nên thống nhất dịch là "máy học".

**Comment by freeloneman** [comment]
Nói luôn kẻo quên, nếu thống nhất cách dịch từ ML như mình đề xuất thì khi dịch tựa cuốn sách, theo cách chọn từ của tác giả - learning yearning có 2 vần ing liền nhau - thì "Machine Learning Yearning" dịch là "Mong máy học mau xong !" ( 2 chữ m liền nhau)
